### ISSUE TITLE
Dockerfiles for Windows images

### ISSUE THREAD

**Issue by sixeyed** [grafana/grafana-docker#101]
It would be great to have Windows versions of the official Grafana image. 

I have a sample [Windows Dockerfile here](https://github.com/sixeyed/docker-windows-workshop/blob/master/part-4/grafana/Dockerfile) which works well, but it takes a different approach from the Linux image. The Windows version deploys the published release rather than building from source.

Looking for feedback here - I'm happy to maintain the Windows variants, and I can also set up CI (it would need to be AppVeyor at this stage, as they're the only service to provide Windows agents).

**Comment by bergquist** [comment]
Great!

Have you seen anyone else publishing different image depending on OS?
I wonder what we should name the windows build. `grafana/grafana-windows` ?

If this would be a official builds we would like to create the project then add you as a member. Would that be ok for you? 

btw. The linux docker image also downloads the binaries now days :) https://github.com/grafana/grafana-docker/blob/master/Dockerfile#L8

**Comment by sixeyed** [comment]
Thanks @bergquist. Typically folks have Windows images as variants in the same repo, with a different tag. See the [NATS](https://hub.docker.com/r/library/nats/tags/) official image - the default `nats` tag (and `nats:1.0.2`) is Linux, and there are also `nats:windowsservercore` and `nats:nanoserver`. 

But if you'd rather have a separate image repo, that's fine with me and I'm happy to be a member.

**Comment by xlson** [comment]
I'm closing this for now as there has been no further interest from the community. If there is a demand we should open a new issue in the main Grafana repository where the docker build lives now ([here](https://github.com/grafana/grafana/tree/master/packaging/docker)).
