### ISSUE TITLE
Allow custom user to be specified

### ISSUE THREAD

**Issue by micheljung** [grafana/grafana-docker#102]
Currently, this docker image uses a hard coded user and group `grafana` within the container. The problem with this, when using volumes, is that all files created by `grafana:grafana` inside the container belong to some "random" user on the host.

In my case, the files created by `grafana:grafana` belong the the user `syslog:crontab` on the host.

Now, unless someone knows how to map container users to host users, it would good if the user/group could be specified as environment variables which would be used like so:

    chown -R ${GRAFANA_USER}:${GRAFANA_GROUP} /etc/grafana

Alternatively, you could define `USER grafana` in the Dockerfile. This can then be overridden by the user. I'm no Docker pro, but I read running containers as root is bad practice. Not sure this applies as well if you change users inside the container.

**Comment by bergquist** [comment]
Sounds like a reasonable solution. A PR would be appreciated.

**Comment by wolkenschieber** [comment]
On my host system the grafana-server is run as user `ntp`. This somehow fails the time synchronization.

**Comment by xlson** [comment]
This will be resolved when we release Grafana 5.1 with the update image tracked in #146.
