### ISSUE TITLE
Rendered image of a panel

### ISSUE THREAD

**Issue by mikefonted** [grafana/grafana-docker#103]
- What Grafana version are you using?
v4.5.1
- What datasource are you using?
Prometheus v1.7.1
- What OS are you running Grafana on?
Official Docker Container (for both Grafana and Prometheus) running on Win10
- What did you do?
Start Grafana container with no extra configuration
`docker run -d -p 3000:3000 grafana/grafana`
Start Prometheus with basic configuration (job_name, metrics_path and targets)
`docker run -d -p 9090:9090 -v C:\prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus`
Data source http settings:
`url = http://localhost:9090`
`access = direct`
Access to the "Direct link rendered image" of a working dashboard panel (i am logged as admin)
![image](https://user-images.githubusercontent.com/6642583/30812382-dfee5dfc-a20a-11e7-8588-848677481719.png)
http://localhost:3000/render/dashboard-solo/db/performance-counters?panelId=1&orgId=1&from=now-5m&to=now&width=1000&height=500&tz=UTC%2B02%3A00&timeout=10
- What was the expected result?
The rendered image
- What happened instead?
500 Internal Server Error
- Grafana container logs
```
docker logs 7dc31ce13565
t=2017-09-25T13:28:03+0000 lvl=info msg=Rendering logger=png-renderer path="dashboard-solo/db/performance-counters?panelId=1&orgId=1&from=now-5m&to=now&width=1000&height=500&tz=UTC%2B02%3A00&timeout=10"
Loading a web page: http://localhost:3000/dashboard-solo/db/performance-counters?panelId=1&orgId=1&from=now-5m&to=now&width=1000&height=500&tz=UTC%2B02%3A00&timeout=10 status: success 10000
t=2017-09-25T13:28:13+0000 lvl=eror msg="Timeout error. You can set timeout in seconds with &timeout url parameter" logger=context userId=1 orgId=1 uname=admin error="Timeout error. You can set timeout in seconds with &timeout url parameter"
t=2017-09-25T13:28:13+0000 lvl=eror msg="Rendering failed." logger=context userId=1 orgId=1 uname=admin error="Timeout error. You can set timeout in seconds with &timeout url parameter"
t=2017-09-25T13:28:13+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/render/dashboard-solo/db/performance-counters status=500 remote_addr=172.17.0.1 time_ms=10035 size=1410 referer=
2017/09/25 13:28:13 http: multiple response.WriteHeader calls
```

**Comment by 0x6373** [comment]
I have the same problem on v4.5.2 running docker, but with Graphite as a backend with access = proxy.
Using "Direct link rendered image" i get 2 errors:
```
Server side error :(
Timeout error. You can set timeout in seconds with &timeout url parameter
```
and 
```
Server side error :(
Rendering failed.
```
docker logs Output:
```
t=2017-10-09T07:49:13+0000 lvl=info msg=Rendering logger=png-renderer path="dashboard-solo/db/caprep_usagemap?orgId=1&var-server=gldimg61&panelId=1&from=1504216800000&to=1506808799999&width=1000&height=500&tz=UTC%2B02%3A00"
Loading a web page: http://localhost:3000/dashboard-solo/db/caprep_usagemap?orgId=1&var-server=gldimg61&panelId=1&from=1504216800000&to=1506808799999&width=1000&height=500&tz=UTC%2B02%3A00 status: success 60000
t=2017-10-09T07:50:13+0000 lvl=eror msg="Timeout error. You can set timeout in seconds with &timeout url parameter" logger=context userId=1 orgId=1 uname=admin error="Timeout error. You can set timeout in seconds with &timeout url parameter"
t=2017-10-09T07:50:13+0000 lvl=eror msg="Rendering failed." logger=context userId=1 orgId=1 uname=admin error="Timeout error. You can set timeout in seconds with &timeout url parameter"
t=2017-10-09T07:50:13+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/render/dashboard-solo/db/caprep_usagemap status=500 remote_addr=10.255.1.37 time_ms=60002 size=1410 referer="http://grafana.local.net/dashboard/db/caprep_usagemap?orgId=1&var-server=gldimg61"
2017/10/09 07:50:13 http: multiple response.WriteHeader calls
```

**Comment by torkelo** [comment]
how long did the query take?

**Comment by scheler** [comment]
@torkelo where do I see the logs that tell how long the query took?  I have debug log enabled in grafana and I see only the same logs the original poster posted above.  I am getting the same timeout error when trying to get a PNG for a certain graph. My setup is almost the same as he has, except I am running grafana 4.6.3 and running the docker container in kubernetes environment.

**Comment by xlson** [comment]
Closing this. Please re-open in the [main](https://github.com/grafana/grafana/issues) Grafana repository if this is still an issue.
