### ISSUE TITLE
Docker official image for grafana

### ISSUE THREAD

**Issue by vaibhavsood** [grafana/grafana-docker#105]
Hi, want to check if an docker official image can be published for grafana? The steps for that are as per here: https://docs.docker.com/docker-hub/official_repos/#how-do-i-create-a-new-official-repository

**Comment by daniellee** [comment]
Yes, I agree we should do this.

**Comment by vaibhavsood** [comment]
Thanks for the response! 

As per Docker's guidelines, the upstream community would need to initiate the process to make an image official, the steps for which are in the link i had posted in my previous comment

It typically involves creating a PR, some reference ones are here: https://github.com/docker-library/official-images/pulls

Also, this is a checklist for new official images: https://github.com/docker-library/official-images/blob/master/NEW-IMAGE-CHECKLIST.md

**Comment by xlson** [comment]
This issue has been moved to the main repository where the docker code now lives.
