### ISSUE TITLE
Add possibility to change --config option broken run.sh script

### ISSUE THREAD

**Issue by verdel** [grafana/grafana-docker#106]
In last merged pull request 8afa40ea0f2a9f8a7ae0f399269c2b163974177e on run.sh string 45 there is "." symbol after
```
--config="$GF_PATHS_CONFIG".
```
This character results in a script error:
```
Failed to parse /etc/grafana/grafana.ini., open /etc/grafana/grafana.ini.: no such file or directory%!(EXTRA []interface {}=[])
```

**Comment by bergquist** [comment]
Thank you for contributing I will repush this asap
