### ISSUE TITLE
Please add to dockerfile

### ISSUE THREAD

**Issue by micioffe** [grafana/grafana-docker#108]
apt-get install -y --no-install-recommends apt-utils

It will take care of apt-utils error
"delaying package configuration, since apt-utils is not installed"

**Comment by tshepang** [comment]
I keep seeing that message, but beyond that, how does it help to install the package? Is the build faster, for example?

**Comment by xlson** [comment]
As long as the container works a few error messages during build time is ok. Thanks for looking into it though.
