### ISSUE TITLE
Plugin names unknown

### ISSUE THREAD

**Issue by AjayKumaraj** [grafana/grafana-docker#114]
Hi, i have to install Pie chart and Diagram plugins using docker env variable but what name should I use as plugin name ???????????? or any specific format like grafana-simple-json-datasource

**Comment by daniellee** [comment]
You can find the plugin ids on their respective plugin pages on grafana.com on the installation tab. The two ids are:

- grafana-piechart-panel
- jdbranham-diagram-panel
