### ISSUE TITLE
Docker build getting failed

### ISSUE THREAD

**Issue by vivekbny** [grafana/grafana-docker#115]
I am trying to build the grafana docker image using docker file and an argument that needs to be passed in docker file. Could you please provide the Download URL to build the docker image Thanks

**Comment by xbblq7n** [comment]
Any update on the above query ?

**Comment by invad0r** [comment]
Did you have a look at build.sh ?

`-build-arg DOWNLOAD_URL=https://s3-us-west-2.amazonaws.com/grafana-releases/master/grafana_latest_amd64.deb`

**Comment by xlson** [comment]
See invad0rs comment or simply use build.sh directly.
