### ISSUE TITLE
Cannot run the built image

### ISSUE THREAD

**Issue by vivekbny** [grafana/grafana-docker#116]
Hi.

I am able to build the image using the docker file. but when running getting the below error

Can you help on this?

docker run -p 8282:3000 grafana4.6
**chown: invalid user: 'grafana:grafana'**

@Dieterbe  @bobrik @pjenvey 

**Docker File:**

FROM debian:jessie

ARG DOWNLOAD_URL

RUN apt-get update && \
    apt-get -y --no-install-recommends install libfontconfig curl ca-certificates && \
    apt-get clean && \
    curl ${DOWNLOAD_URL} > /tmp/grafana-4.6.2.linux-x64.tar.gz && \
    gunzip -d /tmp/grafana-4.6.2.linux-x64.tar.gz && \
        tar -xvf /tmp/grafana-4.6.2.linux-x64.tar && \
    rm /tmp/grafana-4.6.2.linux-x64.tar && \
    curl -L https://github.com/tianon/gosu/releases/download/1.10/gosu-amd64 > /usr/sbin/gosu && \
    chmod +x /usr/sbin/gosu && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

VOLUME ["/var/lib/grafana", "/var/log/grafana", "/etc/grafana"]

EXPOSE 3000

COPY ./run.sh /run.sh

RUN chmod +x /run.sh

ENTRYPOINT ["/run.sh"]

**Comment by xbblq7n** [comment]
Can anybody help on this please

**Comment by xbblq7n** [comment]
Can somebody help on this?

**Comment by invad0r** [comment]
hey @xbblq7n 

I just did ..
```sh
git clone https://github.com/grafana/grafana-docker.git
cd grafana-docker
./build.sh
docker run -p 8282:3000 grafana/grafana:master
```
worked fine. How do you build the image ?

**Comment by xlson** [comment]
Hi @vivekbny, what commands did you use to build this image? I'd suggest using `build.sh`.
