### ISSUE TITLE
Support for ARM

### ISSUE THREAD

**Issue by mcaulifn** [grafana/grafana-docker#117]
Update build to support ARM platform

**Comment by rtmaster** [comment]
+1

**Comment by hatotaka** [comment]
+1

**Comment by xlson** [comment]
We're looking into creating an ARM build for Grafana and when that is finished we will work on the Docker image as well.

Related to grafana/grafana#9633

**Comment by fg2it** [comment]
@xlson Maybe it is already in the pipe but do you plan to add a [manifest](https://docs.docker.com/registry/spec/manifest-v2-2/) so we can pull the right arch image without explicitly specifying it ?

**Comment by xlson** [comment]
@fg2it I wasn't aware there was built in functionality in Docker but that sounds interesting. I'll look into it when we get to the arm images.

**Comment by SeppPenner** [comment]
Is this feature already planned for the near future? I'm just curious as I wanted to run Grafana on my RasPi :heart_eyes: :smirk:

**Comment by xlson** [comment]
@SeppPenner we're currently working on crossplatform builds for Grafana with the help of @fg2it.

**Comment by fg2it** [comment]
@SeppPenner in the meantime, if you can try my [build](https://github.com/fg2it/grafana-on-raspberry/releases) that are also on [docker](https://hub.docker.com/r/fg2it/grafana-armhf/), done the same way as the official one :smile: .

**Comment by SeppPenner** [comment]
Hi @fg2it, thanks. I will try this for the moment. :)

**Comment by RaymondMouthaan** [comment]
I would like to participate to have grafana work on arm and possibly arm64 with the use of manifest list. I have improved several 3th party projects to have this feature and also created my own. As an example: [docker-image-logitech-media-server](https://github.com/RaymondMouthaan/docker-image-logitech-media-server) and [sonweb-docker](https://github.com/RaymondMouthaan/sonweb-docker).

As for now, I will do a fork and hopefully soon a PR with all the changes to make this work.

Cheers,
Raymond

**Comment by fg2it** [comment]
@RaymondMouthaan I think grafana staff is waiting for their arm release before working on that.

**Comment by RaymondMouthaan** [comment]
@fg2it let wait patiently for the staff to have arm release ready :)

**Comment by Nikolay-Ch** [comment]
H! I Can't run container on ARM7 processor (OrangePi Zero H2+) on Armbian OS v.5.38 (based on Debian)

When I run the command: sudo docker run -d --name=grafana -p 3000:3000 grafana/grafana
I get error: standard_init_linux.go:190: exec user process caused “exec format error”

**Comment by SeppPenner** [comment]
I have seen the official ARM support for Grafana. Maybe we will have an official Dockerfile soon: https://grafana.com/grafana/download/5.2.0-beta1?platform=arm :)

**Comment by aospan** [comment]
I have made quick PR:
https://github.com/grafana/grafana-docker/pull/176

for testing you can try my own build aospan/grafana (based on grafana 5.2.1):
docker run -d --name=grafana -p 3000:3000 aospan/grafana

it will automatically choose between arm64v8 and amd64.

**Comment by RaymondMouthaan** [comment]
Create PR #177 to cover amd64, arm32v7, arm64v8 with manifest list support and tags for each architecture. All build by Travis CI triggered by GitHub releases/tags. 

Tested on arm32v7 (Raspberry PI in a docker swarm) and amd64 (Synology NAS), however arm64v8 not tested, since I have no such device available.

[raymondmm/grafana](https://hub.docker.com/r/raymondmm/grafana/tags) is where you can find my images for testing.

**Comment by frostieDE** [comment]
I just testet the arm64v8 version of your docker image, @RaymondMouthaan. Seems to work on my Raspberry Pi 3 :-)

**Comment by RaymondMouthaan** [comment]
@frostieDE, thanks for testing 👍

**Comment by stoinov** [comment]
Confirming it works with Odroid C2

**Comment by aospan** [comment]
tested raymondmm/grafana on arm64v8 (Nvidia Jetson TX2). Works fine.
thanks !

**Comment by xlson** [comment]
This feature request has been moved to the main Grafana repository together with the Docker image.

https://github.com/grafana/grafana/issues/13186
