### ISSUE TITLE
not picking up auth.generic_oauth from environment variables

### ISSUE THREAD

**Issue by qmnonic** [grafana/grafana-docker#123]
I'm trying to setup Auth0 via docker-compose scripts and it doesn't seem to pickup the GF_AUTH_GENERIC_OAUTH configuration via environment variables:

 ```
  GF_AUTH_GENERIC_OAUTH_ENABLED: 'True'
  GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: 'True'
  GF_AUTH_GENERIC_OAUTH_TEAM_IDS: ''
  GF_AUTH_GENERIC_OAUTH_ALLOWED_ORGANIZATIONS: ''
  GF_AUTH_GENERIC_OAUTH_ALLOWED_DOMAINS: '<domains>'
  GF_AUTH_GENERIC_OAUTH_NAME: Auth0
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: <client-id>
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: <client-secret>
  GF_AUTH_GENERIC_OAUTH_SCOPES: openid profile email
  GF_AUTH_GENERIC_OAUTH_AUTH_URL: https://<domain>/authorize
  GF_AUTH_GENERIC_OAUTH_TOKEN_URL: https://<domain>/oauth/token
  GF_AUTH_GENERIC_OAUTH_API_URL: https://<domain>/userinfo
```

Settings page shows values not picked up:
<img width="444" alt="screen shot 2018-01-18 at 11 47 01 am" src="https://user-images.githubusercontent.com/51833/35109824-6a28b50a-fc45-11e7-9339-e3ddb8f995fb.png">

As suggested here - https://community.grafana.com/t/auth0-authentication-support/4875/2

**Comment by cnkk** [comment]
I got the same problem. The env variables are correctly set, but not all of them are used by Grafana.

For example, api_url and token_url cannot be set.

**Comment by DanCech** [comment]
I can't duplicate the issue, this works:
```
GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://domain/authorize ./bin/grafana-server
```
In the logs I see:
```
INFO[03-08|12:03:43] Config overridden from Environment variable logger=settings var="GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://domain/authorize"
```
And it shows up in the settings UI.

Are you sure the settings are getting properly passed into the environment?

**Comment by cnkk** [comment]
@DanCech you are right. It works 🤦
