### ISSUE TITLE
Use nobody user in etc

### ISSUE THREAD

**Issue by mrsiano** [grafana/grafana-docker#124]
Sum up the issue:
when inject ini files to etc/grafana, grafana will fail to start due to  bad permissions.

alternatives:
- follow the /etc/grafana permissions, specially the group id, for any new file that injects there.
- ignore the permissions by using nobody user.

Initial message:
I'm trying to inject a custome configuration to my grafana using the following method:
docker run --name gtest -d -v defaults.ini:/var/lib/grafana/conf/defaults.ini -p 3000:3000 grafana/grafana:master
I also tried to place it under /usr/share/grafana/conf/
but it dose not work. any ideas ?

I would like to do the same actually for datasource file.

dose it supported ?

@bergquist

**Comment by bergquist** [comment]
the docker container currently installs grafana as a debian packages.
So grafana.ini goes into `/etc/grafana/grafana.ini`
datasource configurations goes into `/etc/grafana/provisioning/datasources`
dashboard configurations goes into `/etc/grafana/provisioning/dashboards`

**Comment by mrsiano** [comment]
found it, my grafana.ini file wasn't match the group id in the container.

initially I use grafana.ini with the following permissions:
chgrp grafana grafana.ini

but than I noticed it has diffrent id
-rw-r-----. 1 root grafana 13615 Feb  8 10:26 grafana.ini
-rw-r-x---. 1 root    1002 13614 Feb  8 11:55 grafana123.ini

so I grab the right id from the container which is 107.

**Comment by bergquist** [comment]
We should fix this by using the nobody user.

**Comment by bergquist** [comment]
Our goal was to introduce to fix this before we released 5.0 but right now the beta period is to short for that. This has to wait until 5.1

**Comment by xlson** [comment]
We no longer chown `/etc/grafana` and will be removing chown completely when we release Grafana 5.1. Also 5.0.4 no longer fails to boot when chown fails so for configurations it should be fine to have other owners as long as you configure reads for others (chmod a+x ...)

**Comment by mrsiano** [comment]
thanks!
