### ISSUE TITLE
Installing dashboards / datasources in grafana on container startup

### ISSUE THREAD

**Issue by ddewaele** [grafana/grafana-docker#129]
Hi,

We're running Grafana in a microservice architecture where Grafana is spun up in a docker container.

We can't rely on an existing filesystem (or volume mapping) when starting the container.

We have a number of dashboards / datasources that we would like to install by default (dashboards can be served as json files via HTTP).

There is an API to create datasources / dashboards that we can use, but it's unclear how to fit this into the Docker image. We've tried "wrapping" the grafana/grafana image to do these API calls , but as we need to rely on a running grafana system this is not so easy.

This is how we currently do it, but it's not the most clean solution (to say the least). (for example when using `GF_INSTALL_PLUGINS` it already breaks as it will restart Grafana.

```
echo "Copying grafana dashboard files"
curl -s ${CONFIG_SERVER_URL}/overview-dash.json -o /tmp/overview-dash.json
curl -s ${CONFIG_SERVER_URL}/detail-dash.json -o /tmp/detail-dash.json
curl -s ${CONFIG_SERVER_URL}//grafana-ds.json -o /tmp/grafana-ds.json


echo "Running Grafana"
/run.sh $@ &

echo "Sleeping for 5 seconds to allow Grafana to start. We need to it running to execute the API calls below"
sleep 5

echo "Creating datasource"
curl -v -H 'Content-Type: application/json' -d @/tmp/grafana-ds.json http://localhost:3000/api/datasources

echo "Creating dashboards"
curl -v -H 'Content-Type: application/json' -d @/tmp/overview-dash.json http://localhost:3000/api/dashboards/db
curl -v -H 'Content-Type: application/json' -d @/tmp/detail-dash.json http://localhost:3000/api/dashboards/db

# Keep container alive (hack)
tail -f /dev/null
```

Any ideas on how to best approach this ?

**Comment by invad0r** [comment]
hey,
we have a very similar aproach. We have a seperate container which contains bashscripts, dashahoard-, datasource- and alertnotifications-json and some custom templates.
On inital deploy all is setup via curl and grafan-api then the container shuts down. The container can also be run as a seprate cli to export existing grafana-resources.

**Comment by xlson** [comment]
@ddewaele a companion container using a shared volume and the new [provisioning](http://docs.grafana.org/v5.0/administration/provisioning/#dashboards) feature in Grafana v5.0-beta1 would be your best bet at this time.

If you aren't able to use the newest version I'd suggest creating a companion container that uses the api instead (as @invad0r suggests).
