### ISSUE TITLE
Frequent dashboard timeouts with Grafana docker container

### ISSUE THREAD

**Issue by trinitronx** [grafana/grafana-docker#13]
We are seeing frequent timeouts with our Grafana dashboards on refresh.  The behavior is a blank graph with loading icon for many graphs.

We are using multiple Graphite datasources.  Making requests to those datasources alone (via `curl` or [Dev HTTP Client Chrome Plugin][1]) work fine and are fast.  However, when I try making the same HTTP requests _through_ the Grafana Proxy URL (`/api/datasources/proxy/NN`) I see frequent timeouts and `500` errors.

When watching Grafana logs I see this message repeatedly:

```
[...SNIP...]
2015/08/17 20:51:13 http: proxy error: dial tcp: i/o timeout
2015/08/17 20:51:13 [I] Completed /render 500 Internal Server Error in 30.029153877s
2015/08/17 20:51:22 http: proxy error: dial tcp: i/o timeout
2015/08/17 20:51:22 [I] Completed /render 500 Internal Server Error in 30.028727s
[...SNIP...]
```

When I tried bypassing Grafana entirely and just running requests via `curl` on the host machine, and inside the docker container I saw slowness **_only_ inside the docker container!**

```
$ cat /tmp/curl-format.txt

time_namelookup:  %{time_namelookup}\n
       time_connect:  %{time_connect}\n
    time_appconnect:  %{time_appconnect}\n
   time_pretransfer:  %{time_pretransfer}\n
      time_redirect:  %{time_redirect}\n
 time_starttransfer:  %{time_starttransfer}\n
                    ----------\n
         time_total:  %{time_total}\n
```

### Inside Docker Container:

```
$ sudo docker exec -ti grafana-container  time curl -w "@/tmp/curl-format.txt" -v -s 'http://graphite.example.com/render/?width=586&height=308&from=-4hours&format=json&maxDataPoints=638&target=alias(test.kafka.offsets.TestKafkaOffset.Test.total%2C%20%27Objects%27)'
       time_connect:  35.097
    time_appconnect:  0.000
   time_pretransfer:  35.097
      time_redirect:  0.000
 time_starttransfer:  35.158
                    ----------
         time_total:  35.159

real    0m35.172s
user    0m0.008s
sys     0m0.010s
```

### Outside Docker Container (on same Host):

```
$ time curl -w "@/tmp/curl-format.txt" -v -s 'http://graphite.example.com/render/?width=586&height=308&from=-4hours&format=json&maxDataPoints=638&target=alias(test.kafka.offsets.TestKafkaOffset.Test.total%2C%20%27Objects%27)'
       time_connect:  0.200
    time_appconnect:  0.000
   time_pretransfer:  0.200
      time_redirect:  0.000
 time_starttransfer:  0.263
                    ----------
         time_total:  0.264

real    0m0.273s
user    0m0.004s
sys     0m0.007s
```

I think this may have something to do with a broken network configuration inside the `debian:wheezy` container that this image is based on.  Running a simple `apt-get update` inside the container results in many network connect errors due to IPv6:

```
$ sudo docker exec -ti grafana-container apt-get update
Err http://security.debian.org wheezy/updates Release.gpg
  Cannot initiate the connection to security.debian.org:80 (2610:148:1f10:3::73). - connect (101: Network is unreachable) [IP: 2610:148:1f10:3::73 80]
Ign http://security.debian.org wheezy/updates Release
Err http://security.debian.org wheezy/updates/main amd64 Packages
Err http://security.debian.org wheezy/updates/main amd64 Packages
Err http://security.debian.org wheezy/updates/main amd64 Packages
Err http://security.debian.org wheezy/updates/main amd64 Packages
Err http://security.debian.org wheezy/updates/main amd64 Packages
  Cannot initiate the connection to security.debian.org:80 (2610:148:1f10:3::73). - connect (101: Network is unreachable) [IP: 2610:148:1f10:3::73 80]
```

For what it's worth, it appears `grafana-server` inside the docker container has grabbed the IPv6 loopback address rather than IPv4:

```
root@www-grafana:/usr/share/grafana# cat /etc/debian_version
7.8
root@www-grafana:/usr/share/grafana# uname -a
Linux www-efp-grafana-hnswh 3.10.0-229.7.2.el7.x86_64 #1 SMP Tue Jun 23 22:06:11 UTC 2015 x86_64 GNU/Linux
root@www-grafana:/usr/share/grafana# netstat -tunlp |grep p6
tcp6       0      0 :::3000                 :::*                    LISTEN      1/grafana-server
```

[1]: https://www.sprintapi.com/

**Comment by trinitronx** [comment]
I just tried 2 requests to Graphite from inside the Grafana container... one with IP, and one with the DNS name:

```
root@www-efp-grafana-hnswh:/usr/share/grafana# time curl -w "@/tmp/curl-format.txt" -s -o /dev/null 'http://graphite.example.com/render/?width=586&height=308&from=-4hours&format=json&maxDataPoints=638&target=alias(test.kafka.offsets.TestKafkaOffset.Test.total%2C%20%27Objects%27)'
time_namelookup:  35.052
       time_connect:  35.101
    time_appconnect:  0.000
   time_pretransfer:  35.102
      time_redirect:  0.000
 time_starttransfer:  35.164
                    ----------
         time_total:  35.164

real    0m35.175s
user    0m0.010s
sys     0m0.006s

root@www-efp-grafana-hnswh:/usr/share/grafana# time curl -w "@/tmp/curl-format.txt" -s -o /dev/null http://123.45.67.89/render/?width=586&height=308&from=-4hours&format=json&maxDataPoints=638&target=alias(test.kafka.offsets.TestKafkaOffset.Test.total%2C%20%27Objects%27)'
time_namelookup:  0.000
       time_connect:  0.049
    time_appconnect:  0.000
   time_pretransfer:  0.049
      time_redirect:  0.000
 time_starttransfer:  0.112
                    ----------
         time_total:  0.112

real    0m0.124s
user    0m0.009s
sys     0m0.004s
```

`time_namelookup:  35.052` with the name... therefore my problem appears to be due to DNS.  This container is running inside of Kubernetes, so there is some issue in SkyDNS.   I'll close this issue.

**Comment by bentekkie** [comment]
Did you ever solve this issue?

**Comment by trinitronx** [comment]
as it turned out, yes we did fix this issue.  It seems that it was a combination of various issues:

1. Old version of Kubernetes & skydns had issues talking to `kube-apiserver` due to token and cert auth problems, so services were not populated by `kube2sky`
2. Grafana was pointing at an old version of Graphite without support for limiting the max data points returned by the JSON API (caused dashboard slowness
3. Grafana was configured to use file storage for sessions on an NFS volume... which made it slow
4. For some reason, Grafana never cleaned up session files, and health checks were creating hundreds of thousands of them
5. Grafana would start up very slowly because the docker image entrypoint was running a `chown -R` on the sessions dir (100s of thousands of file operations over NFS = BAD!)


So the solution was manyfold:

1. Switch Grafana to use Redis sidecar container in the same pod for session storage
2. Upgraded Kubernetes to latest stable (1.4), & fixed kube-dns auth issues by fixing cert SANs
3. Upgraded Graphite to later version (can't remember version at the moment)
4. Switched from sqlite file dashboard storage to RDS MariaDB

This fixed all of our issues and now Grafana is very snappy!
