### ISSUE TITLE
How do I configure filesystem permissions on files mapped from host to the grafana container user?

### ISSUE THREAD

**Issue by sandersaares** [grafana/grafana-docker#132]
Given that the Grafana container creates a user "grafana" in group "grafana", what is the correct pattern to assign access rights to files mapped externally? Without making those files world-readable to the users on the host, that is.

I am unsure how to do it because the user/group "grafana" does not exist on the host. So how can I assign correct permissions? I would expect, for example, Grafana to run as root in the container (thereby having access to all files I map into the container).

**Comment by xlson** [comment]
With how the current docker image is structured handling permissions is a bit harder than necessary and Grafana 5.1 will release with a new image that remedies this (it's worked on [here](https://github.com/grafana/grafana-docker/tree/image-improvements)).

The grafana user in current (<5.1) version of Grafana has id 104. If you have sudo rights on your computer you could chown the files & folders that you wish to be able to map into Grafana to that id.

In 5.1 and later you will be able to run the image as any user id which means that you could start the container with the same user id that you have outside of the container.

You would be able to do this (on linux):
```bash
ID=$(id -u)
GROUP=$(id -g)
docker run -p 3000:3000 -v "$PWD/data:/var/lib/grafana" \
    --user $ID:$GROUP grafana/grafana:5.1.0
```
