### ISSUE TITLE
Enabling plugins

### ISSUE THREAD

**Issue by a-dawg** [grafana/grafana-docker#133]
hey
It would be great to be able to enable plugins through an environment variable as we are already able to install plugins but not to enable them.
Example for the zabbix plugin and as discussed in https://github.com/alexanderzobnin/grafana-zabbix/issues/398 at the end of the run.sh `curl -v --basic -XPOST "admin:$GF_SECURITY_ADMIN_PASSWORD@localhost:3000/api/plugins/alexanderzobnin-zabbix-app/settings?enabled=true" -d ''`
could be called at the end of the run.sh script ?
this would be very useful whenever you need to restart your containers.

**Comment by xlson** [comment]
This is something that should be supported in Grafana itself. I've created an issue on the main repository to track it (grafana/grafana#11409).
