### ISSUE TITLE
Ability to install plugins manually

### ISSUE THREAD

**Issue by stp72** [grafana/grafana-docker#134]
The environment where the container is running is a sandbox and doesn't have internet access.  It would be great to have a way to install plugins offline.

**Comment by xlson** [comment]
You should be able to create your own Dockerfile with our image as a base and install the needed plugins.

**Comment by xlson** [comment]
Example `Dockerfile` with preinstalled plugins:
```
FROM grafana/grafana:5.0.0
RUN mkdir -p /opt/grafana-plugins
RUN grafana-cli --pluginsDir /opt/grafana-plugins plugins install mtanda-histogram-panel
ENV GF_PATHS_PLUGINS=/opt/grafana-plugins
```
