### ISSUE TITLE
grafana.ini: config not used

### ISSUE THREAD

**Issue by mkuger** [grafana/grafana-docker#139]
I mount /etc/grafana/ as a volume on my host. Inside the directory is the grafana.ini file with my configuration.
However, this file has no effect. When looking at server config in the grafana dashboard in admin/settings I can see that the values I stated in my grafana.ini are not shown (e.g. hostname). If I open a bash inside the container using `docker exec -it MY_CONTAINER bash` I see that /etc/grafana/grafana.ini contains the values I provide in the volume.
docker logs shows me this output:
`t=2018-03-05T20:05:10+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2018-03-05T20:05:10+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2018-03-05T20:05:10+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2018-03-05T20:05:10+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2018-03-05T20:05:10+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2018-03-05T20:05:10+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
t=2018-03-05T20:05:10+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.log.mode=console"`

How can I config the instance without creating a new Dockerfile?
Thanks for your support! Best, Michael

**Comment by xlson** [comment]
Mounting `grafana.ini` to `/etc/grafana.ini` should work. I just verified it with the release build of 5.0.0. Can you verify that you don't see your settings in http://<your host>/admin/settings? If so, can your share your an example that reproduces your issue with docker or docker-compose. Also, what does your hostname line look like in grafana.ini?

**Comment by abelgana** [comment]
I kind of have the same question. Should the config be mounted to /etc/grafana.ini or /etc/grafana/grafana.ini?

**Comment by xlson** [comment]
@abelgana It should be mounted to `/etc/grafana/grafana.ini`, sorry about the confusion (I've updated my last comment to reflect the correct path).

**Comment by xlson** [comment]
This is the most basic example of using volume mappings with the config that I could think of. 

Download this `grafana.ini` (the only change from the defaults is to enable anonymous access) https://gist.githubusercontent.com/xlson/56b5c0d49265aa0bf1d41faaa4383ec5/raw/8e4fdc2323bf669fea0ba82cd183cb5735331203/grafana.ini

Run this command in the folder where you put the downloaded config file:
`docker run --rm -v "$PWD/grafana.ini:/etc/grafana/grafana.ini" -p 3000:3000 grafana/grafana:5.0.0`

You should now be able to access http://localhost:3000/ without being logged in. Does this work for you?

**Comment by xlson** [comment]
I'm closing this as I haven't heard back from you. Let me know if you're still having problems.

**Comment by gcoloz** [comment]
Still have problems with that. Correctly copied a grafana.ini in /etc via docker cp (and verified it of course), but still the container doesn't take the setting. Can't understand why, honestly.

**Comment by xlson** [comment]
@gcoloz what version of the Grafana docker image are you using?

**Comment by gcoloz** [comment]
Hi @xlson , thank you for your quick reply. 

Of course I've restarted the container, version is: Grafana v5.1.3 (087143285)

**Comment by xlson** [comment]
@gcoloz Could you test downloading the contents of this gist and then running the test-script, and then tell me what happened? The expected behavior is to start seeing xorm logs after restart (and that is what happens on my machine). 

https://gist.github.com/xlson/e3407795db2de20c60da10e14378350b

**Comment by gcoloz** [comment]
I have an output, that's correct I think, e.g.:
 t=2018-06-12T13:00:04+0000 lvl=info msg="[SQL] select * from alert - took: 267.127µs" logger=sqlstore.xorm

If it can help, by going on Server Admin I see:
log_queries | true

Am I supposed to see xorm there?

Thank you.

**Comment by xlson** [comment]
@gcoloz Ok. You getting the sql statement in the log as well as the log_queries | true in the server admin shows that modifying the grafana.ini file by copying it in and then restarting the container works for you.

- What are you doing different than what that script is doing?
- What settings are you trying to change?

**Comment by lavoiedn** [comment]
I've experienced a similar issue trying to modify the [`data` config in `[paths]`](http://docs.grafana.org/installation/configuration/#data). Seems like the environment variable was always getting precedence over our `/etc/grafana/grafana.ini`.

Fixed it by setting `GF_PATHS_DATA=""`, which then caused it to start using the config in our `grafana.ini`:

```
[paths]
data = /path/to/data
```

When the environment variable is not overriden, I get these line in the logs:

```
t=2018-09-04T16:55:56+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_DATA=/var/lib/grafana"
[...]
t=2018-09-04T16:55:56+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
```

When I set `GF_PATHS_DATA=""` I get the expected:

```
t=2018-09-04T17:05:09+0000 lvl=info msg="Path Data" logger=settings path=/path/to/data
```

Docker image version: `5.1.3`

**Comment by xlson** [comment]
@lavoiedn This is a different issue and comes from the fact that `GF_PATHS_DATA` is set by the run-script in the Grafana docker image as a way to control where we put the data dir. It's more of an implementation detail than a bug.

**Comment by xlson** [comment]
@lavoiedn In all honesty, I don't think we specify it in the documentation. I will make sure that is properly listed if it isn't already.
