### ISSUE TITLE
[Feature request] Add google auth by environment variable in Docker Image

### ISSUE THREAD

**Issue by lparet-yseop** [grafana/grafana-docker#145]
Like AWS Profiles, it will be interesting to add Google oauth at container starting

Related to this documentation section : [http://docs.grafana.org/installation/configuration/#auth-google](url)

For example:
```
docker run \
  --name grafana \
  -e "GF_GOOGLE_OAUTH_CLIENT_ID=YOUR_CLIENT_ID" \
  -e "GF_GOOGLE_OAUTH_CLIENT_SECRET=YOUR_CLIENT_SECRET" \
  grafana/grafana
```
It will enable the google auth and configure automatically with env variables and default configuration

I will do a PR when I will have time to implement that

**Comment by xingxing** [comment]
Do you have a plan on this issue? @lparet-yseop
