### ISSUE TITLE
 Network Error: Bad Gateway(502) when trying to connect to InfluxDB

### ISSUE THREAD

**Issue by BurnyHa** [grafana/grafana-docker#150]
Hi there,
just installed the latest version of the docker on a QNAP  TS-251A.
I also have InfluxDB (1.4.3) running on the same system. I write data from a Raspberry into the database.
Now I tried to add the database as a data source in Grafana but when testing the connection i get 
Network Error: Bad Gateway(502).
The connection parameters should be ok as if the Raspberry uses them successfully.
Both containers are set to network mode NAT.

I tried http://localhost:8086
In the Grafana console on the QNAP i get this entry. 
2018/04/01 22:49:59 http: proxy error: dial tcp 127.0.0.1:8086: getsockopt: connection refused 

When I use http://192.168.0.3:8086  i get
2018/04/01 22:48:22 http: proxy error: dial tcp 192.168.0.3:8086: i/o timeout

Anybody an idea what`s wrong?

![grafana](https://user-images.githubusercontent.com/37987438/38178327-b5312654-3610-11e8-9eb3-4da567308e29.JPG)

**Comment by xlson** [comment]
My guess would be iptables or something else related to Docker and networking. I'm afraid this kind of question is a bit out of scope for this repository. I would try Docker Community Slack or some other Docker oriented forum.

Good luck.
