### ISSUE TITLE
Unable to Install plugins - Permission denied. Make sure you have write access to plugindir

### ISSUE THREAD

**Issue by vjsairam** [grafana/grafana-docker#154]
I am trying to install plugins in the latest version of grafana through helm, image: "grafana/grafana:5.1.0"

I see an error with the below message, 

GF_PATHS_DATA='/var/lib/grafana' is not writable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later
installing natel-plotly-panel @ 0.0.4
from url: https://grafana.com/api/plugins/natel-plotly-panel/versions/0.0.4/download
into: /var/lib/grafana/plugins
 Error: ✗ Could not create /var/lib/grafana/plugins/natel-plotly-panel. Permission denied. Make sure you have write access to plugindir
 NAME:
   Grafana cli plugins install - install &lt;plugin id&gt; &lt;plugin version (optional)&gt;
 USAGE:
   Grafana cli plugins install [arguments...]

**Comment by jecnua** [comment]
I think this is connected to the 5.1.0 breaking change with the docker image.
- http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later
You need to update directory rights or run grafana with the old user id.

**Comment by xlson** [comment]
As jecnua mentioned this is related to file permissions. Is `/var/lib/grafana` a volume by any chance? For Grafana to be able to install plugins user id `472` needs write access to `/var/lib/grafana/plugins`. And if you use sqlite for the database it also require write access to `/var/lib/grafana/grafana.db`.

Alternatively, if the volumes are from a previous version of Grafan you could just run the container with the old Grafan user id `104` and your permissions since before should keep working.

**Comment by vjsairam** [comment]
@jecnua / @xlson  I am not migrating the versions and I am doing a new deployment using Helm charts.

**Comment by xlson** [comment]
Can you check the file permissions for `/var/lib/grafana/plugins`? They should be `472` but I presume they are different for some reason. Is this your own packaging?

**Comment by vjsairam** [comment]
drwxr-sr-x 4 104 107 6144 Mar 21 14:19 briangann-datatable-panel
drwxr-sr-x 5 104 107 6144 Apr 24 08:42 digiapulssi-organisations-panel
drwxr-sr-x 4 104 107 6144 Mar 21 14:18 grafana-piechart-panel
drwxr-sr-x 4 104 107 6144 Mar 21 14:19 jdbranham-diagram-panel
drwxr-sr-x 4 104 107 6144 Apr 11 02:34 mtanda-histogram-panel
drwxr-sr-x 4 104 107 6144 Mar 25 10:58 natel-discrete-panel
drwxr-sr-x 4 104 107 6144 Mar 21 14:18 natel-plotly-panel
drwxr-sr-x 4 104 107 6144 Apr 24 08:52 raintank-worldping-app
drwxr-sr-x 6 104 107 6144 Apr 11 02:34 ryantxu-ajax-panel
drwxr-sr-x 4 104 107 6144 Apr 11 02:34 vonage-status-panel

No, this is not my packaging.

**Comment by xlson** [comment]
The plugins folder is owned by the userid/groupid we used for Grafana in previous versions. That's either a persistant volume or those plugins are bundled with the helm packaging but my guess would be a persistent volume given the different sets of dates. In that case, you should be able to change the ownership of everything below `/var/lib/grafana/plugins` to `472` and the boot should keep going.

**Comment by vjsairam** [comment]
The issue is resolved after updating the helm charts and doing a fresh deployment. Thanks @xlson
