### ISSUE TITLE
v5.1.0 fails with aws credentials injected via environment variable

### ISSUE THREAD

**Issue by jecnua** [grafana/grafana-docker#156]
Grafana: grafana/grafana:5.1.0
OS: Ubuntu 16.04 / Kernel 4.4.0-1035-aws

Docker version:

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

==============

Running a docker container with couldwatch support, as for http://docs.grafana.org/installation/docker/#configuring-aws-credentials-for-cloudwatch-support fails now on 5.1.0.

Like:

```
  -e "GF_AWS_PROFILES=default" \
  -e "GF_AWS_default_ACCESS_KEY_ID=YOUR_ACCESS_KEY" \
  -e "GF_AWS_default_SECRET_ACCESS_KEY=YOUR_SECRET_KEY" \
  -e "GF_AWS_default_REGION=us-east-1" \
```

Same identical config used to ran with no problem in 4.x.
I tested the credentials and they are working correctly.

The error logged is the following:

`t=2018-04-30T12:52:51+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="Failed to call cloudwatch:ListMetrics, NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"`

`t=2018-04-30T13:08:00+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"`

Adding the token/secrets on grafana datasource page directly works.

**Comment by jecnua** [comment]
Ghost in the machine. After 30 minutes working on it it's going again. Must have been an error my side. Closing this and sorry for the spam.

**Comment by xlson** [comment]
No worries, glad you got it sorted.
