### ISSUE TITLE
permissions using docker-compose

### ISSUE THREAD

**Issue by jtktam** [grafana/grafana-docker#159]
the system was running fine prior to the latest upgrade, now i am getting a permission denied (read only error) on the /var/lib/grafana (own by root/root of the host) 

i put in the user: "104" in my docker-compose file but it still has the same error

  grafana:
    user: "104"
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./config/grafana:/etc/grafana
      - /var/docker/grafana/lib:/var/lib/grafana
      - /var/docker/grafana/log:/var/log/grafana
    networks:
      - default

i removed the /var/docker/grafana directory (rm -rf) and let docker make the new directories, it is still same error

any help? thanks

**Comment by DanCech** [comment]
what are the permissions on `./config/grafana` and `/var/docker/grafana` ?

**Comment by jtktam** [comment]
most of the other docker containers i am running works fine with the jtam/root users.. i would like to use the same docker-compose file with multiple machines/users without having to find the UID.. is there any reason why grafana works differently than others? (like prometheus, etc)

**Comment by DanCech** [comment]
They most likely run as root, which is a bad idea if you care about security.  You can do that with `user: "0:0"` if that isn't a concern.

**Comment by jtktam** [comment]
ok thanks!
