### ISSUE TITLE
Install/Use SSL

### ISSUE THREAD

**Issue by RedSpid3r** [grafana/grafana-docker#161]
hello, wondering how i can install/setup ssl on this docker image?

I know i need to change the config file to use https but i need to generate a self-signed ssl certificate first but not sure how to do that on this image.

any help (or links to documentation on how to do it) would be appreciated

**Comment by xlson** [comment]
Hi! Please send questions like this to the community site in the future: https://community.grafana.com

If you want to self sign I would suggest that you find a guide for how to do that and to it outside of Grafana and then either volume map the resources into your container or extend the container and add your certificate and key to the new image.

This guide might help:
https://community.hortonworks.com/articles/85365/enable-ssl-for-grafana.html
