### ISSUE TITLE
grafana datasources yaml doesn't support environment value

### ISSUE THREAD

**Issue by like-inspur** [grafana/grafana-docker#163]
I create a grafana instance with grafana/grafana:5.1.2 image. I want to config different datasources for different grafana. So I config a datasources.yaml under /etc/grafana/provisioning like this:
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://$PROMETHEUS_SERVER:9090

And I create an environment value for $PROMETHEUS_SERVER，but no value on grafana web page.
![1](https://user-images.githubusercontent.com/18571465/40160511-79b1c7ca-59e0-11e8-8682-a1a0eb9d7f6f.png)
![2](https://user-images.githubusercontent.com/18571465/40160521-8140bdb6-59e0-11e8-81ec-24acc76040f6.png)

@tail @torkelo @pjenvey @Dieterbe @bobrik

**Comment by torkelo** [comment]
there is a feature request for this in Grafana repo I think

**Comment by xlson** [comment]
This feature request has been moved to the main Grafana repository https://github.com/grafana/grafana/issues/12896
