### ISSUE TITLE
Grafana container keeps restarting

### ISSUE THREAD

**Issue by jonathan599** [grafana/grafana-docker#168]
Hi,

I tried to install grafana but it doesn't come up.The config is not changed at all.

In browser i get this issue : 502 Bad Gateway

and docker container logs are:

standard_init_linux.go:178: exec user process caused "permission denied"
standard_init_linux.go:178: exec user process caused "permission denied"
standard_init_linux.go:178: exec user process caused "permission denied"
standard_init_linux.go:178: exec user process caused "permission denied"
standard_init_linux.go:178: exec user process caused "permission denied"
standard_init_linux.go:178: exec user process caused "permission denied"
standard_init_linux.go:178: exec user process caused "permission denied"
standard_init_linux.go:178: exec user process caused "permission denied"
standard_init_linux.go:178: exec user process caused "permission denied"
standard_init_linux.go:178: exec user process caused "permission denied"
standard_init_linux.go:178: exec user process caused "permission denied"

Please can you help

**Comment by marefr** [comment]
Please read http://docs.grafana.org/guides/whats-new-in-v5-1/#improved-docker-image-breaking-change and follow links.

**Comment by jonathan599** [comment]
thanks for ur comments @marefr.

I am trying to implement [dockprom ](https://github.com/stefanprodan/dockprom/) but i get the above error as well. I believe that docker compose is written for grafana:4.6.3 and also image used is Grafana:4.6.3. Kindly assist

**Comment by DanCech** [comment]
@jonathan599 what are you trying to do exactly? dockprom appears to be using 4.6.3, are you trying to alter their docker-compose to use 5.1.x?

**Comment by jonathan599** [comment]
@DanCech No, i am starting dockprom as it is. All other containers are up but i see only grafana restarting. and i see this logs as "permission denied". i also tried changing permission of ./setup.sh but doesnt seem to work. 

tried some crude way.Promethus runs on on http://xx.xx.xx.xx:3000/ so i tried modifying in Prometheus.json the url to ttp://xx.xx.xx.xx:3000/ from "url":"http://prometheus:9090" even that didnt work.

**Comment by DanCech** [comment]
There is something wrong on your system, I was able to run the dockprom install instructions without any issues.

```
git clone https://github.com/stefanprodan/dockprom
cd dockprom

ADMIN_USER=admin ADMIN_PASSWORD=admin docker-compose up -d
```
The link @marefr posted above is not applicable to dockprom since it uses `grafana:4.6.3`

**Comment by xlson** [comment]
- What version of docker are you using? Any chance you're on Fedora or Centos and running the docker package instead of the docker-ce one?
- What OS are you on?

**Comment by jonathan599** [comment]
Docker version 1.13.1 and OS is linux

**Comment by xlson** [comment]
@jonathan599 Sounds like you're running docker engine. You may have to upgrade to Docker Community Edition instead.

**Comment by jonathan599** [comment]
Maybe.. thanks @xlson
