### ISSUE TITLE
[auth.generic_oauth] Login provider didn't return an email address

### ISSUE THREAD

**Issue by lekpamartin** [grafana/grafana-docker#180]
We receive this error message : Login provider didn't return an email address.

But in grafana log, we see this:

t=2018-07-20T15:24:55+0000 lvl=dbug msg="HTTP GET <auth_url>: 200 OK {\"mail\":\"testemail@mondomain.com\",\"scope\":[\"mail\",\"username\"],\"grant_type\":\"authorization_code\",\"realm\":\"/AccessManagement\",\"username\":\"MONUSER\",\"token_type\":\"Bearer\",\"expires_in\":86399,\"client_id\":\"test-grafana\",\"access_token\":\"7999de5d-087d-4e72-8fd5-bea25ee1cd07\"}"

Any suggestion ? 

 Grafana v5.3.0-pre1 (commit: 5578097)

**Comment by marefr** [comment]
This is Grafana related and not docker so should be in the Grafana repo. 

Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.
