### ISSUE TITLE
[Bug] Unrecognized envionment variable

### ISSUE THREAD

**Issue by lekpamartin** [grafana/grafana-docker#182]
Grafana don't read somes environment variable. 

For example, I defined GF_AUTH_GENERIC_OAUTH_TLS_CLIENT_CA="ca_file" to set tls_client_ca for auth.generic_oauth.

It is the same if i want to set tls_skip_verify_insecure. 

It work if I edit in configuration file for exemple /etc/grafana/grafana.ini.

**Comment by xlson** [comment]
Thanks for reporting this issue. It seems to be an oversight on our part. I will create a new issue in the main Grafana issue to resolve this problem.

**Comment by lekpamartin** [comment]
Thanks for actions
