### ISSUE TITLE
v2.5.0

### ISSUE THREAD

**Issue by rainerhahnekamp** [grafana/grafana-docker#22]
Hi, is there a time plan when the Dockerfile gets upgraded to version 2.5.0?

**Comment by DarrellMozingo** [comment]
+1

**Comment by NorthIsUp** [comment]
+1

**Comment by vinhlh** [comment]
+1

**Comment by NorthIsUp** [comment]
until there is an official image https://hub.docker.com/r/northisup/grafana2.5/

**Comment by torkelo** [comment]
fixed, sorry for not addressing this in time :(
