### ISSUE TITLE
Using custom config.js

### ISSUE THREAD

**Issue by bill0ute** [grafana/grafana-docker#24]
Hi guys,

Really enjoying playing with Grafana so far !
I would like the container to use my own config.js, which specify the datasources like this :
```javascript
datasources: {
    influxdb: {
        type: 'influxdb',
        url: "http://ip:port/db/mydb",
        username: 'user',
        password: 'pass',
        default: true
    },
    grafana: {
        type: 'influxdb',
        url: "http://ip:port/db/grafana",
        username: 'user',
        password: 'pass',
        grafanaDB: true
    },
},
```
My guess is I just need to map the correct volume, to force Docker to use my config.js.

`docker run -d -p 3000:3000 -v config.js:/??/config.js grafana/grafana`

But what is the path in the container of the config,js used by Grafana ?

**Comment by jakubholynet** [comment]
Is `config.js` still used in 2.x??

**Comment by bill0ute** [comment]
Ah, may be not.
Is it still possible to store Grafana data in InfluxDB 0.9 ?
