### ISSUE TITLE
Unable to run grafana container with SELinux enabled due to gosu 1.5 bug

### ISSUE THREAD

**Issue by rmbrad** [grafana/grafana-docker#27]
Attempting to run the grafana image using:
```
docker run -d --name=grafana -p 3000:3000 grafana/grafana
```
fails with the following error message when SELinux is enabled:
```
error: failed switching to "grafana": fchown fds permission denied
```
This appears to be due to a bug in gosu 1.5 (see discussion at docker-library/mongo#56 and tianon/gosu#8;) which has since been fixed. I've tested rebuilding the image with gosu versions 1.6 and 1.7 and both resolve the issue. 

I've also noticed that using the ```-t``` option to the docker run command to create a pseudo-tty will workaround the issue as well.

**Comment by Dieterbe** [comment]
ok, so is anything actionable here? or are you just letting us know?

**Comment by rmbrad** [comment]
Really just letting you know (since I'm fine just adding the ```-t``` option as a workaround) and documenting for other users.

But if you update the ```Dockerfile``` to use gosu 1.7 by changing:
```
curl -L https://github.com/tianon/gosu/releases/download/1.5/gosu-amd64 > /usr/sbin/gosu
```
to
```
curl -L https://github.com/tianon/gosu/releases/download/1.7/gosu-amd64 > /usr/sbin/gosu
```
then it will just work in SELinux without the need for the ```-t``` option.

**Comment by AxelVoitier** [comment]
I am affected by this, running on CentOS 7.

**Comment by jangaraj** [comment]
FYI https://github.com/monitoringartist/grafana-xxl permission fixed - you can use it or you can wait for official update.

**Comment by ksingh7** [comment]
Guys i am still hitting this bug , ``setenforce 0`` is a temporary fix.

But looking for official fix

**Comment by jangaraj** [comment]
@ksingh7 did you pull/use latest grafana:2.6.0 docker image?

**Comment by ksingh7** [comment]
@jangaraj not very sure i pulled grafana/grafana , so i hope it should be default latest and greatest ?

**Comment by jangaraj** [comment]
Pls provide information how to replicate your problem. It should be already fixed.

**Comment by jangaraj** [comment]
@Dieterbe gosu 1.5 is back - any idea why? This issue should be reopened and fixed.
```
[root@dockerhost ~]# docker run --rm -ti --entrypoint bash grafana/grafana
root@dca668cb1051:/# /usr/sbin/gosu -h
Usage: /usr/sbin/gosu user-spec command [args]
   ie: /usr/sbin/gosu tianon bash
       /usr/sbin/gosu nobody:root bash -c 'whoami && id'
       /usr/sbin/gosu 1000:1 id

/usr/sbin/gosu version: 1.5 (go1.5.1 on linux/amd64; gc)
```
@ksingh7 use community version `monitoringartist/grafana-xxl` with correct gosu 1.7:
```
[root@dockerhost ~]# docker run --rm -ti --entrypoint bash monitoringartist/grafana-xxl
root@8a78ea6d1fa0:/# /usr/sbin/gosu -h
Usage: /usr/sbin/gosu user-spec command [args]
   ie: /usr/sbin/gosu tianon bash
       /usr/sbin/gosu nobody:root bash -c 'whoami && id'
       /usr/sbin/gosu 1000:1 id

/usr/sbin/gosu version: 1.7 (go1.5.1 on linux/amd64; gc)
```

**Comment by bergquist** [comment]
We had some merge conflicts in this repo that caused broken containers.
Should be fixed by now.

@ksingh7 Could you please test the new 3.0.1 container?

**Comment by ksingh7** [comment]
@bergquist 
So should i run ``docker run -d --name=grafana -p 3000:3000  grafana/grafana:3.01`` command to test new container 3.0.1 ?

**Comment by bergquist** [comment]
@ksingh7 yes please :)

Im no docker export but the gosu issue should be fixed today.
