### ISSUE TITLE
error: failed switching to "grafana": fchown fds permission denied

### ISSUE THREAD

**Issue by lockwobr** [grafana/grafana-docker#30]
When I do a docker run:

```
docker run \
  -d \
  -p 3000:3000 \
  --name=grafana \
  --volumes-from grafana-storage \
  grafana/grafana:2.6.0
```

I get the error:
error: failed switching to "grafana": fchown fds permission denied
I get this error for both latest and 2.6.0 but if I use develop It works.
Any ideas whats with this?

**Comment by verhage** [comment]
Got this error too. Seems to be a gosu bug. Develop doesn't use gosu, so that must be why it works. Are you deploying on CentOS 7?

**Comment by lockwobr** [comment]
Yes I am.

```
$ uname -a
Linux Monitoring 3.10.0-327.4.5.el7.x86_64 #1 SMP Mon Jan 25 22:07:14 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
```

**Comment by verhage** [comment]
It's not my commit, I ran into the issue myself while trying grafana. Switching to the develop branch resolved this issue :)

**Comment by roman-vynar** [comment]
This is selinux enabled on the host machine causing this.
If you do `setenforce 0` and re-try ther ewill not be any issues.
No idea about the proper fix.
