### ISSUE TITLE
Grafana fails to start with with persistent data volume on host

### ISSUE THREAD

**Issue by jtblin** [grafana/grafana-docker#32]
I've tried mounting a persistent data volume as recommended (on Mac with docker-machine) and grafana does not want to start with following error:

```
 $ docker run -d -v `pwd`/dev/data/grafana:/var/lib/grafana --name grafana-storage busybox:latest
04e4bc71b005846de8e138cddc929e74158cb341bb8fb81bdfac68b263ead24f 
$ docker run \
>   -d \
>   -p 3000:3000 \
>   --name=grafana \
>   --volumes-from grafana-storage \
>   grafana/grafana
20b94fd4a3b8a92a98d98ec79151bf78e0ceba05935a86704995b0731e610618
$ docker logs grafana
2016/02/29 09:38:23 [I] Starting Grafana
2016/02/29 09:38:23 [I] Version: 2.6.0, Commit: v2.6.0, Build date: 2015-12-14 14:18:01 +0000 UTC
2016/02/29 09:38:23 [I] Configuration Info
Config files:
  [0]: /usr/share/grafana/conf/defaults.ini
  [1]: /etc/grafana/grafana.ini
Command lines overrides:
  [0]: default.paths.data=/var/lib/grafana
  [1]: default.paths.logs=/var/log/grafana
Paths:
  home: /usr/share/grafana
  data: /var/lib/grafana
  logs: /var/log/grafana

2016/02/29 09:38:23 [I] Database: sqlite3
2016/02/29 09:38:23 [I] Migrator: Starting DB migration
2016/02/29 09:38:23 [log.go:75 Fatal()] [E] fail to initialize orm engine: Sqlstore::Migration failed err: unable to open database file
```

I have tried various combinations, with `docker-compose`, without it, mounting the volume directly, with a data container, etc. and nothing works. It only works if I don't mount any volume (but then I lose the data on container restart...).

Does grafana/sqlite3 try to write with a specific user or something?

**Comment by gillesdemey** [comment]
I'm having the same problem on my machine.

OSX 10.11.4
docker 1.10.3
docker-compose 1.6.2

Any ideas what might be causing this?

**Comment by matevarga** [comment]
It breaks for me even if I don't mount volumes.

**Comment by bergquist** [comment]
@jtblin grafana will try to create data/grafana.db if it does not exist. So write and read permissions are required for the data directory. 

"Sqlstore::Migration failed err: unable to open database file" indicated that something is wrong with permissions.

**Comment by jangaraj** [comment]
Do you have this problem also with current dockerized Grafana 3?

**Comment by mickey** [comment]
Got the same issue on last grafana image.
```yaml
grafana:
  image: grafana/grafana:latest
  links:
    - influxdb
  depends_on:
    - influxdb
  ports:
    - "3000:3000"
  volumes:
    - ./grafana/data:/var/lib/grafana
```

```
grafana_1   | 2016/06/02 07:15:35 [I] Starting Grafana
grafana_1   | 2016/06/02 07:15:35 [I] Version: 3.0.3, Commit: v3.0.3, Build date: 2016-05-23 08:58:31 +0000 UTC
grafana_1   | 2016/06/02 07:15:35 [I] Configuration Info
grafana_1   | Config files:
grafana_1   |   [0]: /usr/share/grafana/conf/defaults.ini
grafana_1   |   [1]: /etc/grafana/grafana.ini
grafana_1   | Command lines overrides:
grafana_1   |   [0]: default.paths.data=/var/lib/grafana
grafana_1   |   [1]: default.paths.logs=/var/log/grafana
grafana_1   |   [2]: default.paths.plugins=/var/lib/grafana/plugins
grafana_1   | 	Environment variables used:
grafana_1   |   [0]: GF_SECURITY_ADMIN_USER=foobar
grafana_1   |   [1]: GF_SECURITY_ADMIN_PASSWORD=*********
grafana_1   | Paths:
grafana_1   |   home: /usr/share/grafana
grafana_1   |   data: /var/lib/grafana
grafana_1   |   logs: /var/log/grafana
grafana_1   |   plugins: /var/lib/grafana/plugins
grafana_1   |
grafana_1   | 2016/06/02 07:15:35 [I] Database: sqlite3
grafana_1   | 2016/06/02 07:15:35 [I] Migrator: Starting DB migration
grafana_1   | 2016/06/02 07:15:35 [log.go:84 Fatal()] [E] fail to initialize orm engine: Sqlstore::Migration failed err: unable to open database file
grafana_1   |
docker_grafana_1 exited with code 1
```

**Comment by jangaraj** [comment]
Try:
```
chmod 777 ./grafana/data
```

**Comment by hinok** [comment]
I have the same problem. Doing something like this:

```
sudo chmod -R 777 data
```

works for a moment. I added yesterday issue https://github.com/grafana/grafana/issues/5338
Running chmod allows for running server. Then I can log in, but after that I always get the same error:

```
2016/06/11 23:21:03 [middleware.go:78 initContextWithUserSessionCookie()] [E] Failed to start session%!(EXTRA *os.PathError=open /var/lib/grafana/sessions/3/9/3951b0c6f901d3f9: permission denied)
2016/06/11 23:21:03 [I] Completed 192.168.99.1 hinok "GET / HTTP/1.1" 302 Found 29 bytes in 2747us
2016/06/11 23:21:03 [middleware.go:78 initContextWithUserSessionCookie()] [E] Failed to start session%!(EXTRA *os.PathError=open /var/lib/grafana/sessions/e/1/e1d67c346b5553af: permission denied)
2016/06/11 23:21:03 [I] Completed 192.168.99.1 hinok "GET /login HTTP/1.1" 302 Found 24 bytes in 6959us
2016/06/11 23:21:03 [middleware.go:78 initContextWithUserSessionCookie()] [E] Failed to start session%!(EXTRA *os.PathError=open /var/lib/grafana/sessions/6/c/6cf2a4fb634f3e4f: permission denied)
2016/06/11 23:21:03 [I] Completed 192.168.99.1 hinok "GET / HTTP/1.1" 302 Found 29 bytes in 1850us
2016/06/11 23:21:03 [middleware.go:78 initContextWithUserSessionCookie()] [E] Failed to start session%!(EXTRA *os.PathError=open /var/lib/grafana/sessions/6/5/6555ccf964f5e81f: permission denied)
2016/06/11 23:21:03 [I] Completed 192.168.99.1 hinok "GET /login HTTP/1.1" 302 Found 24 bytes in 3153us
2016/06/11 23:21:03 [middleware.go:78 initContextWithUserSessionCookie()] [E] Failed to start session%!(EXTRA *os.PathError=open /var/lib/grafana/sessions/b/8/b8856271a7c01bca: permission denied)
2016/06/11 23:21:03 [I] Completed 192.168.99.1 hinok "GET / HTTP/1.1" 302 Found 29 bytes in 1873us
```

**Comment by jangaraj** [comment]
@hinok It's problem of your docker setup not a Grafana issue - https://github.com/grafana/grafana/issues/5338.  Why you are not using recommended storage container model?
https://github.com/grafana/grafana-docker#grafana-container-with-persistent-storage-recommended

If you want to use dumb volume (`-v`), then you need to manage permissions on docker host directory manually (TBH chmod 777 is not secure workaround) + you are using probably some non native Docker implementation (docker machine/boot2docker), which introduces another potential permissions problems, because there is directory sharing between your host <-> docker host (VM) <-> docker container.

**Comment by hinok** [comment]
@jangaraj Thanks, using https://github.com/grafana/grafana-docker#grafana-container-with-persistent-storage-recommended solves the problem.

I know that 777 in real is 666 (a bit evilish).
I just want to run some local tests which requires graphite + grafana, for that I need some persistent storage. I found in the docker docs that volumes are a way to solve that problem.

**Comment by cvielma** [comment]
Same issue on:
- Mac OS X (10.11.6)
- Docker 1.11.1

Following @jangaraj recommendation to have a docker volume worked for me.

**Comment by bergquist** [comment]
Closing this

**Comment by Morriz** [comment]
For kubernetes users this is still an issue I assume. I have not found a workaround for the lack of `--volumes-from` in kubernetes. Is there such a workaround? Setting path perms with initContainer was not successful for me. I've come to believe that is a dead end, as I've seen many reports about initial creation working, but writing in folders afterwards is disallowed.

**Comment by marcel-dempers** [comment]
Same issue and like @Morriz it's also a dead end on Kubernetes for me. Had to resort to using Postgres PaaS service and hook up my grafana pod to that.

**Comment by xlson** [comment]
You should definitely be able to do use Grafana with persistent volumes (https://kubernetes.io/docs/concepts/storage/volumes/) in kubernetes but this is not currently something we have documentation for. My advice would be to reach out to a kubernetes community for help. The next version of Grafana (5.1) will have a new image which should make this easier as we remove the default volumes and make it possible to run the container as any user.

**Comment by DanCech** [comment]
Note that the root uid and gid are always 0, so you can replace `$(id -u root):$(id -g root)` with `0:0`
