### ISSUE TITLE
Allow grafana to be run as root

### ISSUE THREAD

**Issue by timcharper** [grafana/grafana-docker#38]
Is there a really good reason to not run Grafana as root within Docker? I'm using a plugin which gives each container it's own IP address (Weave) and I'd like to just have Grafana listen on `:80`, but the created Grafana user doesn't have permission to do so.

**Comment by bergquist** [comment]
I'm closing this issue based on this conversation: https://github.com/grafana/grafana-docker/pull/40 

Since running processes as root in containers it bad practice we do not want to encourage it.
