### ISSUE TITLE
Fail to start/build grafana/grafana

### ISSUE THREAD

**Issue by rjes** [grafana/grafana-docker#43]
Hi!
I'm having trouble with grafana and docker:
`# docker run -i -p 3000:3000 grafana/grafana
...
docker: Error response from daemon: Container command '/run.sh' not found or does not exist..
`
So I cloned this repo and tried to build the image by my self:
`~/grafana-docker# ./build.sh
...
Container command '/bin/sh' not found or does not exist.
`
I tried to setup a link in the Dockfile between /bin/bash and /bin/sh without success.
Have anyone a clue how to solve this?

**Comment by jangaraj** [comment]
Try to pull latest image first `docker pull grafana/grafana:latest` and then try again `docker run -i -p 3000:3000 grafana/grafana`

**Comment by rjes** [comment]
It wasn't a grafana-docker issue but a docker daemon issue, it's working now.
