### ISSUE TITLE
[Question] - MySQL storage instead of volume?

### ISSUE THREAD

**Issue by Bonn93** [grafana/grafana-docker#45]
Could a MySQL server be used instead of the persistent disk storage / docker volume? This would make things a bit easier as we could run multiple databases and store all the data outside of the docker / docker host? Is that an option?

**Comment by bergquist** [comment]
@Bonn93 you can configure Grafana to use mysql, postgres or sqlite3. http://docs.grafana.org/installation/configuration/#database
