### ISSUE TITLE
Separate volume for plugins directory makes it impossible to store /var/lib/grafana in total on a persistent disk

### ISSUE THREAD

**Issue by JorritSalverda** [grafana/grafana-docker#48]
In kubernetes I mount a persistent disk to /var/lib/grafana, however plugins i install in /var/lib/grafana/plugins don't get persisted to that disk.

Presumably because the Dockerfile has those 2 in separate volumes:

`VOLUME ["/var/lib/grafana", "/var/lib/grafana/plugins", "/var/log/grafana", "/etc/grafana"]`

For what reason is this specified as a separate volume? Wouldn't it make sense to combine the 2?

**Comment by jangaraj** [comment]
Nope. Then plugin codes will be always stored on the disk. Personally I don't like this behavior, but if you like it, then just specify additional persistent disk for `/var/lib/grafana/plugins`.

**Comment by woodsaj** [comment]
I think nested volumes are a terrible idea.  @bergquist you added the commit, given that /var/lib/grafana is already a volume, why is /var/lib/grafana/plugins also a volume?

Surely any use case that warrants splitting /var/lib/grafana and /var/lib/grafana/plugins across two volumes would be better handled by the user specifying the volume details in the Docker run command.

**Comment by JorritSalverda** [comment]
Creating a second persistent disk for just a couple of plugins seems overkill, especially since the smallest PD size with Google Cloud is 1GB.

As we run Grafana in Kubernetes there's no fixed machine it runs on, it can run anywhere in the cluster, the PD follows the container. It makes sense to optimize containers for these scenarios instead of sticking with the old pet approach :)

I created a 'fork' without the volumes at https://hub.docker.com/r/travix/grafana/. It persists the plugins to the same disk now.

Thanks for Grafana, it rocks!

**Comment by bergquist** [comment]
@woodsaj My assumption was that people wanted to reuse the same plugin volume for multiple grafana instances. But in hindsight I totally agree with you that those things should be solved with docker run parameters. 

Removing the plugin volume from the Dockerfile would cause problems for those of have mapped the persistent disk but it should only be a matter for reinstalling the plugins.

**Comment by fg2it** [comment]
@bergquist If I understand correctly you agree to change to a single volume `/var/lib/grafana`, right ? when can we expect the changes to take place ? would you like a PR ?
