### ISSUE TITLE
SSL certificates not loaded

### ISSUE THREAD

**Issue by alexnederlof** [grafana/grafana-docker#5]
When using Google Auth in this docker image, it will throw an exception:

    [login_oauth.go:40 OAuthLogin()] [E] login.OAuthLogin(NewTransportWithCode): Post https://accounts.google.com/o/oauth2/token: x509: failed to load system roots and no roots provided

That's because no SSL certificates are present in the image.

As a work-around you can add the certs from your host system

    -v /etc/ssl/certs:/etc/ssl/certs

**Comment by torkelo** [comment]
thanks for reporting this. Do you know what to do to install them in a docker container? A step I need to execute or package I need to include in the Dockerfile?
