### ISSUE TITLE
Chrome : Data Source not working

### ISSUE THREAD

**Issue by Quentinvarquet** [grafana/grafana-docker#52]
Hello,

I tried to use your container (working with another graphite container.)

When I try to add a new data source with Chrome, I have many errors (see screenshot): 

![image](https://cloud.githubusercontent.com/assets/7962157/18626109/2dad8914-7e53-11e6-9428-1d481e95b3fd.png)

If I do exactly the same on Internet Explorer, everything is working well, I can add a data source and create some dashboards 

![image](https://cloud.githubusercontent.com/assets/7962157/18626129/5282ea0e-7e53-11e6-85c1-677f054601c9.png)

So I created all my dashboards, they are all working well. But if I try to check them with Google Chrome, I have an empty dashboard (always loading).

**Dashboard from IE :** 

![image](https://cloud.githubusercontent.com/assets/7962157/18626188/ae832148-7e53-11e6-99e5-7125d1500483.png)

**Dashboard from Chrome**

![image](https://cloud.githubusercontent.com/assets/7962157/18626226/f53e1994-7e53-11e6-8920-b7ece6b49e51.png)

If I check the Google Chrome console : 

![image](https://cloud.githubusercontent.com/assets/7962157/18626252/1cfd8b54-7e54-11e6-8ef0-66cf290212b4.png)

Do you know how to fix it ?

Thank you.

**Comment by RobTS** [comment]
Experiencing something similar, though not browser-specific, rather the datasource and charts working sometimes and sometimes not.

**Comment by torkelo** [comment]
this is security that most browser have, if you want to access Graphite directly from your browser you need configure graphite with CORS headers

**Comment by Quentinvarquet** [comment]
Hello,

That's a problem. I tried to configure it but it's still not working. Do you have an URL where I can configure graphite with CORS ?

**Comment by torkelo** [comment]
https://www.google.se/search?q=graphite+CORS&oq=graphite+CORS&aqs=chrome..69i57j0l5.2167j0j4&sourceid=chrome&ie=UTF-8
