### ISSUE TITLE
GF_SECURITY_ADMIN_PASSWORD does not work but gets recognized

### ISSUE THREAD

**Issue by MTRNord** [grafana/grafana-docker#55]
I have 

`GF_SECURITY_ADMIN_PASSWORD="1199" `

as my ENV var. In the log it says `msg="Config overriden from Environment variable" logger=settings var="GF_SECURITY_ADMIN_PASSWORD=*********"` but if i want to login with admin/1199 it does fail.

Log says:

`lvl=eror msg="Invalid username or password" logger=context userId=0 orgId=0 uname= error="Invalid Username or Password"`

**Comment by MTRNord** [comment]
Ok I had persistent and the old password was used. Closing

**Comment by Bexanderthebex** [comment]
I'm sorry but how did you resolve this?

**Comment by MTRNord** [comment]
@Bexanderthebex I need to investigate if I still have the files somewhere.

**Comment by oneoneonepig** [comment]
Same problem with the same log here. Can't login using GF_SECURITY_ADMIN_USER=admin and GF_SECURITY_ADMIN_PASSWORD=[RandomGeneratedSecret]
