### ISSUE TITLE
Plugins Version

### ISSUE THREAD

**Issue by ricardobur** [grafana/grafana-docker#59]
I am trying to specify the version of the plugins in my docker-compose.yml. I have tried to put it as <plugin> <version> as specified in [grafana plugins docs](http://docs.grafana.org/plugins/installation/) but it has been impossible to install the required version. I think it could be fixed of the way that GF_INSTALL_PLUGINS is read, making possible to read the var with values like the next example:

GF_INSTALL_PLUGINS=grafana-piechart-panel 1.1.4,mtanda-histogram-panel 0.1.5

Would it be possible to add the possibility to add plugins version?

**Comment by bergquist** [comment]
Should be fixed by #60

**Comment by ricardobur** [comment]
Thank you :D
