### ISSUE TITLE
unable to save dashboard using external directory

### ISSUE THREAD

**Issue by amnonh** [grafana/grafana-docker#63]
I'm trying to attach an external directory to the grafana image.

All my attempt to make the dashboard files writable have failed.

The json files located under grafana/dashboards locally

I first tried:
sudo docker run -d -v $PWD/grafana/dashboards:/var/lib/grafana/dashboards:Z -i -p 3000:3000 \
      -e "GF_AUTH_BASIC_ENABLED=false" \
      -e "GF_AUTH_ANONYMOUS_ENABLED=true" \
      -e "GF_AUTH_ANONYMOUS_ORG_ROLE=Admin" \
      -e "GF_INSTALL_PLUGINS=grafana-piechart-panel" \
     -e "GF_DASHBOARDS_JSON_ENABLED=TRUE" \
     -e "GF_DASHBOARDS_JSON_PATH=/var/lib/grafana/dashboards" \
      --name agraf grafana/grafana:3.1.0

Becuase of the chown command running in the container, I both loose ownership of my local json files and the files are not writeable (no save button).

I also tried placing the files not under /var/lib/grafana (/var/lib/grafana1).

In that case, I do not loose the ownership, it seems that the grafana user inside the container do have the right permissions but still no save button.

**Comment by bergquist** [comment]
Dashboards loaded from disk are never writeable. If you want to update your dashboard from within grafana you have to save them to the database.
