### ISSUE TITLE
[Bug] latest tag is not updated to v4.0.2

### ISSUE THREAD

**Issue by Starefossen** [grafana/grafana-docker#64]
The `grafana/grafana:latest` tag on [Docker Hub](https://hub.docker.com/r/grafana/grafana/tags/) has not been updated to v4.0.2. I noticed this originally in a comment on the Docker Hub page.

<img width="1296" alt="screen shot 2016-12-15 at 14 04 11" src="https://cloud.githubusercontent.com/assets/968267/21225037/669ce77c-c2cf-11e6-9e1b-06e573bb643e.png">

**Comment by Starefossen** [comment]
Also, there is an inconsistency with what tags have been pushed to Docker Hub and the latest commit to this repository:  f3fb44e. If you are pushing images on a manual basis I would suggest setting up a CI job to do the docker push based on commits to this repository.

**Comment by bergquist** [comment]
Latest tag have now been set to 4.0.2.

Yea we are still pushing the builds automatically. We are gonna start working on improving this process soonish. As always.. its a matter of time :)
