### ISSUE TITLE
Incorrect use of functions

### ISSUE THREAD

**Issue by PabloLefort** [grafana/grafana-docker#70]
Hi! Sending a lot of test metrics, e.g: `test 1.000000 1484148820` i want to represent the count of the hits.

When trying: `hitcount(test, '20s')` only represents a horizontal line and also the same result using: `summarize(test, '20s')`.

What will be the correct way to make work this example?

Thanks in advance!

**Comment by bergquist** [comment]
This is seems like a question for the [graphite project](https://github.com/graphite-project)
