### ISSUE TITLE
No LICENSE.md in project

### ISSUE THREAD

**Issue by rvdmei** [grafana/grafana-docker#73]
Would it be possible to make this project explicitly open source? Maybe add the same license as the Grafana project. 

To elaborate a bit more. GitHub terms explicitly permit viewing and forking of public projects, they do not enforce an open source license to the project, this means that normal copyright otherwise applies. I can't do anything with the project besides viewing and forking if a license is absent.

**Comment by bergquist** [comment]
License file have been added. Project settings will be updated shortly.
