### ISSUE TITLE
[Feature request] Add dashboard import by environment variable

### ISSUE THREAD

**Issue by bvis** [grafana/grafana-docker#74]
One important feature in containers is the automation of initial configuration. In the grafana docker image this possibility is missing.

One container that runs this image is not useful without an initial manual configuration. This wouldn't be a problem if we don't count with the volatility of containers.

Adding the option of automatically import dashboards by environment variables would be a huge improvement.

For example:

```
docker run \
  --name grafana \
  -e GF_INSTALL_DASHBOARDS=123,456 \
  grafana/grafana
```
Which would import the dashboards available in grafana.net with these ids. If when they are imported the references to the datasources already exist in the container it would use them directly. If not, the first time, it should show the option of which datasources to use.

**Comment by shaunwarman** [comment]
Or have an `ONBUILD` here that copies current working directory `.json` and imports this for use at startup.

**Comment by zplizzi** [comment]
Also, the option to import a dashboard from file (say, in a mounted volume) would be useful. That way initial configurations can be checked into source control.

**Comment by mccormd** [comment]
Hi, one option would be to update the run.sh to do it.  Here is a script that I am using, which I mount into the official container and call by overriding --entrypoint:

```
#!/bin/bash

# Script to configure grafana datasources and dashboards.
# Intended to be run before grafana entrypoint...
# Image: grafana/grafana:4.1.2
# ENTRYPOINT [\"/run.sh\"]"

GRAFANA_URL=${GRAFANA_URL:-http://localhost:3000}
#GRAFANA_URL=http://grafana-plain.k8s.playground1.aws.ad.zopa.com
DATASOURCES_PATH=${DATASOURCES_PATH:-/etc/grafana/datasources}
DASHBOARDS_PATH=${DASHBOARDS_PATH:-/etc/grafana/dashboards}

# Generic function to call the Vault API
grafana_api() {
  local verb=$1
  local url=$2
  local params=$3
  local bodyfile=$4
  local response
  local cmd

  cmd="curl -L -s --fail -H \"Accept: application/json\" -H \"Content-Type: application/json\" -X ${verb} -k ${GRAFANA_URL}${url}"
  [[ -n "${params}" ]] && cmd="${cmd} -d \"${params}\""
  [[ -n "${bodyfile}" ]] && cmd="${cmd} --data @${bodyfile}"
  echo "Running ${cmd}"
  eval ${cmd} || return 1
  return 0
}

wait_for_api() {
  while ! grafana_api GET /api/user/preferences
  do
    sleep 5
  done 
}

install_datasources() {
  local datasource

  for datasource in ${DATASOURCES_PATH}/*.json
  do
    if [[ -f "${datasource}" ]]; then
      echo "Installing datasource ${datasource}"
      if grafana_api POST /api/datasources "" "${datasource}"; then
        echo "installed ok"
      else
        echo "install failed"
      fi
    fi
  done
}

install_dashboards() {
  local dashboard

  for dashboard in ${DASHBOARDS_PATH}/*.json
  do
    if [[ -f "${dashboard}" ]]; then
      echo "Installing dashboard ${dashboard}"
      if grafana_api POST /api/dashboards/db "" "${dashboard}"; then
        echo "installed ok"
      else
        echo "install failed"
      fi
    fi
  done
}

configure_grafana() {
  wait_for_api
  install_datasources
  install_dashboards
}

echo "Running configure_grafana in the background..."
configure_grafana &
/run.sh
exit 0
```

Hope it helps.

**Comment by Aakansha-Talati** [comment]
Is the environment variable now available to import the dashboard?

**Comment by xlson** [comment]
Since Grafana 5.0 it's possible to provision dashboards from file, read about it [here](http://docs.grafana.org/administration/provisioning/#dashboards). Automatic import directly from grafana.net is still not available but might perhaps be a useful extension to provisioning.

**Comment by bvis** [comment]
@xlson It would be nice to have automatic import from grafana.net, it would be awesome!

**Comment by xlson** [comment]
This feature depends on grafana/grafana#10786

**Comment by xlson** [comment]
Moved to https://github.com/grafana/grafana/issues/12895
