### ISSUE TITLE
DNS failure due to /etc/hosts and /etc/resolv.conf permissions

### ISSUE THREAD

**Issue by paulcgt** [grafana/grafana-docker#78]
Hi there,

Im using Grafana 4.1.1 (grafana/grafana:latest) and I found that certain webhook endpoints do not work from within the Docker container. The do work from outside of the container though if I were to query them using CURL or a browser.

The error log notes DNS lookup failures, and this appears to be because the grafana user running grafana-server in the container does not have read permissions on /etc/hosts and /etc/resolv.conf.

When I add read permissions (chmod 644) to /etc/hosts and /etc/resolv.conf then the webhooks work.

I notice the run.sh already does a chown on certain folders. Does it make sense to add the following to the run.sh script?
```
chmod 644 /etc/hosts
chmod 644 /etc/resolve.conf
```

Paul.

**Comment by xlson** [comment]
Thanks for sharing your issue. My guess would be that it wasn't Grafana but rather the version of Docker you were running at the time that caused this issue (or something else in the environment).
