### ISSUE TITLE
HTTP Error Bad Gateway: datasource : prometheus

### ISSUE THREAD

**Issue by shamimgeek** [grafana/grafana-docker#83]
Hello 

I am getting HTTP Error Bad Gateway with all version > 4.0

CentOS Linux release 7.1.1503 (Core)

docker image version : image: grafana/grafana:4.2.0-beta1
datasource : prometheus

**Comment by daniellee** [comment]
If you think this is a bug, can you open an issue on the main Grafana repo instead. If you just need help, then the [community forum](https://community.grafana.com) is the best place to ask questions.
