### ISSUE TITLE
Why remove curl from the grafana image?

### ISSUE THREAD

**Issue by mccormd** [grafana/grafana-docker#84]
Hi, I'd like to use the official Grafana image but add in a very simple script to automatically load datasources and dashboards upon start up.  This all seemed to be going well until I discovered that curl is removed in the grafana Dockerfile.  Is there any way we could keep it?

**Comment by jangaraj** [comment]
Ideal microservice docker image doesn't contain any additional binaries, which are not required for that microservice. Why you can't use additional container with curl, which will communicate with grafana container/API?

**Comment by mccormd** [comment]
Using a sidecar container just to get curl back which was in the original image then removed feels unnecessarily complex.  How about we add the capability to automatically load datasources and dashboards into the official grafana image?

Here's an extension to the run.sh that takes care of this fuctionality: -

~~~
#!/bin/bash -x
    
    # David McCormick
    
    # Script to configure grafana datasources and dashboards.
    # Intended to be run before grafana entrypoint...
    # Image: grafana/grafana:4.1.2
    # ENTRYPOINT [\"/run.sh\"]"
    
    GRAFANA_URL=${GRAFANA_URL:-http://localhost:3000}
    #GRAFANA_URL=http://grafana-plain.k8s.playground1.aws.ad.zopa.com
    DATASOURCES_PATH=${DATASOURCES_PATH:-/etc/grafana/datasources}
    DASHBOARDS_PATH=${DASHBOARDS_PATH:-/etc/grafana/dashboards}
    
    # Generic function to call the Vault API
    grafana_api() {
      local verb=$1
      local url=$2
      local params=$3
      local bodyfile=$4
      local response
      local cmd
    
      cmd="curl -L -v --fail -H \"Accept: application/json\" -H \"Content-Type: application/json\" -X ${verb} -k ${GRAFANA_URL}${url}"
      [[ -n "${params}" ]] && cmd="${cmd} -d \"${params}\""
      [[ -n "${bodyfile}" ]] && cmd="${cmd} --data @${bodyfile}"
      echo "Running ${cmd}"
      eval ${cmd} || return 1
      return 0
    }
    
    wait_for_api() {
      while ! grafana_api GET /api/user/preferences
      do
        sleep 5
      done 
    }
    
    install_datasources() {
      local datasource
    
      for datasource in ${DATASOURCES_PATH}/*.json
      do
        if [[ -f "${datasource}" ]]; then
          echo "Installing datasource ${datasource}"
          if grafana_api POST /api/datasources "" "${datasource}"; then
            echo "installed ok"
          else
            echo "install failed"
          fi
        fi
      done
    }
    
    install_dashboards() {
      local dashboard
    
      for dashboard in ${DASHBOARDS_PATH}/*.json
      do
        if [[ -f "${dashboard}" ]]; then
          echo "Installing dashboard ${dashboard}"
          if grafana_api POST /api/dashboards/db "" "${dashboard}"; then
            echo "installed ok"
          else
            echo "install failed"
          fi
        fi
      done
    }
    
    configure_grafana() {
      wait_for_api
      install_datasources
      install_dashboards
    }
    
    echo "Running configure_grafana in the background..."
    configure_grafana &
    /run.sh
    exit 0
~~~

**Comment by jangaraj** [comment]
You may need the same for organizations/users as well.  There is more sophisticated solution for that - https://www.terraform.io/docs/providers/grafana/

**Comment by pjenvey** [comment]
This was merged but I'll note:

Agreed that Docker images should strive for the ideal of being as small/isolated as possible. However there's some good arguments for always including a wget/curl equivalent (in pretty much any container):

o not uncommon to utilize it for convenient bootstrapping of configuration, e.g. introducing such things into the docker cmd:
export GF_DEFAULT_INSTANCE_NAME=\`wget -qO- http://169.254.169.254/latest/meta-data/instance-id`
(see http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html for more examples)
o @mccormd's relevant point on sidecar/custom images: is it really worth the inconvenience just to shave what, a couple mb?

It's an even more important utility in Grafana's case where configuration is done via REST calls.

An alpine based container (#44) would be a large improvement towards isolating/shaving space off the container image size (and even the very small alpine includes wget). I'd love to see that resolved.
