### ISSUE TITLE
[Feature Request] Add dasboards dir as exportable volume.

### ISSUE THREAD

**Issue by toni-moreno** [grafana/grafana-docker#87]
I would like install some scripted dashboards on a docker image and I can not do it if we can not export this directory.

Thank you very much!

**Comment by anthu** [comment]
You can mount the volume wherever you want to and pass the configuration as ENV variables:

```
GF_DASHBOARDS_JSON_ENABLED
GF_DASHBOARDS_JSON_PATH
```

eg:  
```
docker run \
-v $(pwd)/dashboards:/dashboards \
-e GF_DASHBOARDS_JSON_ENABLED='true' \
-e GF_DASHBOARDS_JSON_PATH='/dashboards' \
-p 3000:3000 grafana/grafana
```

**Comment by DasIch** [comment]
@anthu  The grafana user inside the container won't have permission to access `/dashboards`, so this doesn't solve the problem.

**Comment by anthu** [comment]
Have you tried it? That's exactly how I'm using it right now (read only dashboards) with no issues.

**Comment by xlson** [comment]
I'm closing this as the issue is so old. Let me know if you're still having issues.
