### ISSUE TITLE
Grafana not starting with persistent data volume on kubernetes PVC (persistent volume claim)

### ISSUE THREAD

**Issue by prasenforu** [grafana/grafana-docker#88]
I am running grafana in container/pod in kubernetes.

To reuse of grafana data I mounted /var/lib/grafana persistent data volume on kubernetes PVC (persistent volume claim)

Grafana container logs saying 

```
chown: changing ownership of '/var/lib/grafana/log/grafana': Operation not permitted
chown: changing ownership of '/var/lib/grafana/log': Operation not permitted
chown: changing ownership of '/var/lib/grafana/lib/grafana': Operation not permitted
chown: changing ownership of '/var/lib/grafana/lib': Operation not permitted
chown: changing ownership of '/var/lib/grafana/run/secrets/kubernetes.io/serviceaccount': Operation not permitted
chown: changing ownership of '/var/lib/grafana/run/secrets/kubernetes.io': Operation not permitted
chown: changing ownership of '/var/lib/grafana/run/secrets': Operation not permitted
chown: changing ownership of '/var/lib/grafana/run': Operation not permitted
chown: changing ownership of '/var/lib/grafana': Operation not permitted

```

FYI mounted volume permission given 777 but same ....

Please help

**Comment by daniellee** [comment]
Maybe these might help:

- https://kubeapps.com/charts/stable/grafana

- Or check out the docker compose script linked to in this blog post: https://medium.com/intel-sdi/monitor-the-systems-you-love-on-kubernetes-6dcb256bd63c

- https://hub.docker.com/r/whereisaaron/grafana-kubernetes/

**Comment by prasenforu** [comment]
Thanks Lee.

**Comment by 0x656b694d** [comment]
Hi @prasenforu,
Don't you mind sharing the solution?

**Comment by prasenforu** [comment]
Use this image ```prasenforu/grafana```

**Comment by juniorrocha** [comment]
Hi, 
use this this parameter in your .yaml file:
~~~
containers:
      - name: grafana
         image: grafana/grafana:latest
         securityContext:
             runAsUser: 0
         env: 
         ...
~~~
This parameter changes default user from grafana (472) to root (0)
I tried to run container and change permissions with grafana user but was unsuccessful, so this change solves the volume mounting problem. 

Full .yaml example:
~~~
apiVersion: v1
kind: Service
metadata:
  name: service-grafana-standalone
  labels:
    name: service-grafana-standalone
    role: service
spec:
  ports:
      - name: http
        port: 80
        targetPort: 3000
  selector:
    name: grafana-standalone
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: grafana-standalone
spec:
  serviceName: "service-grafana-standalone"
  replicas: 1
  template:
    metadata: 
      labels:
        name: grafana-standalone
        role: standalone
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          securityContext:
            runAsUser: 0
          env: 
          - name: GF_SERVER_DOMAIN
            value: "my.domain"
          - name: GF_SERVER_ROOT_URL
            value: "http://my.domain"
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: volume-grafana-standalone
  volumeClaimTemplates:
    - metadata:
        name: volume-grafana-standalone  
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
~~~

**Comment by Yannic92** [comment]
I would not recommend runnign grafana as root. Grafana changed this on purpose. It's a security feature. Instead you could run an init-container that changes the owner of the directory to the grafana user.

    ...
      initContainers:
      - name: grafana-init
        image: grafana/grafana:latest
        command:
        - "sh"
        - "-c"
        - "chown -R 472:472 /var/lib/grafana"
        volumeMounts:
        - name: volume-grafana-standalone
          mountPath: /var/lib/grafana
        securityContext:
          runAsUser: 0
      volumes:
        - name: volume-grafana-standalone
          persistentVolumeClaim:
            claimName: grafana-pvc
