### ISSUE TITLE
KairosDB data source missing in versions other than 2.6.0

### ISSUE THREAD

**Issue by abhagupta** [grafana/grafana-docker#89]
I found the Kairos DB option for datasource in version 2.6.0, but not in any other greater versions. Is there a reason it was removed?

**Comment by DanCech** [comment]
It was moved to a plugin in 3.x https://grafana.com/plugins/grafana-kairosdb-datasource

**Comment by abhagupta** [comment]
Thanks @DanCech , I found it and got the Kairos db running in latest grafana docker image.. However, I could not get the Annotation set up for Kairos db.  I do not see an option of attaching Annotations with Kairos data source. I only see Grafana datasource.

![image](https://cloud.githubusercontent.com/assets/825965/25248822/7fedf722-25c4-11e7-8a18-691ba75a922f.png)


Version of Kairos Plugin : v2.0.1
Grafana docker : latest

Please let me know if I need to create a seperate issue for this.

**Comment by daniellee** [comment]
@abhagupta It seems like KairosDB does not have support for annotations in Grafana unfortunately.
