### ISSUE TITLE
`--config` flag not accepted as command

### ISSUE THREAD

**Issue by fentas** [grafana/grafana-docker#91]
**Use case:**
```sh
docker secret create "grafana.config" "./grafana.ini"
docker service create \
  --secret "grafana.config" \
  grafana/grafana:4.3.2 --config=/run/secrets/grafana.config
```
This will not work. My guess is, because the entrypoint script [run.sh] already specifies `--config` flag.

**Comment by fentas** [comment]
As a workaround do it like this
```sh
docker secret create "grafana.config" "./grafana.ini"
docker service create \
  --secret "grafana.config" \
  --entrypoint "sh" \
  grafana/grafana:4.3.2 -c 'ln -fs /run/secrets/grafana.config /etc/grafana/grafana.ini; /run.sh'
```

Note this will only work with the latest Docker (17.05) because of `--entrypoint`.
https://github.com/moby/moby/pull/29228

**Comment by simonvanderveldt** [comment]
+1 for this, it should definitely be possible to pass a custom `--config` option to grafana.
A simple fix might be using an env var for this that defaults to the current value?

**Comment by bergquist** [comment]
PR would be appreciated.

**Comment by jmaitrehenry** [comment]
I just made a PR for that. I use an env var as suggested by @simonvanderveldt.
For the name, I used `GF_PATHS_CONFIG` like other paths (data, plugins, and logs).

**Comment by jmaitrehenry** [comment]
@bergquist Could we merge it?
