### ISSUE TITLE
Docker-Compose with Grafana stops when Postgres is not yet up.

### ISSUE THREAD

**Issue by nmarus** [grafana/grafana-docker#92]
Essentially the issue occurs when having grafana/grafana in a docker-compose file with a postgres instance. If postgres is not all the way initialized (and yes, Grafana has link to postgres container), Gragana will shutdown. This seem to be the case in that postgres on initial startup takes a moment to set everything up. This assumes you are setting up the database through ENV variables. 

Here is the errr from the docker logs of the grafana container right before it stops.

```
t=2017-06-03T19:59:44+0000 lvl=eror msg="Fail to initialize orm engine" logger=sqlstore error="Sqlstore::Migration failed err: dial tcp 172.19.0.4:5432: getsockopt: connection refused\n"
```

Locally, I can get around this by having a "restart always" for the Grafana container and when Grafana restarts, postgres is up and all is well. 

On other platforms, specifically AWS ECS, when creating a service/task, this shuts down the entire service/task assuming you have both postgres and grafana containers set to "essential".  I know this might not be a typical setup as many will probably have a centralized postgres server outside of their ECS Service definition.

Either way, I have been able to compensate for  this by installing netcat as one of the apt dependencies in the Dockerfile and prepending the following to the the beginning of run.sh:

```bash
#!/bin/bash -e

# if database type is defined, equals postgress, and host is defined
if [ ! -z ${GF_DATABASE_TYPE+x} ] \
&& [ "$GF_DATABASE_TYPE" == "postgres" ] \
&& [ ! -z ${GF_DATABASE_HOST+x} ]; then
  # split GF_DATABASE_HOST into array of host and port
  DATABASE=(${GF_DATABASE_HOST//:/ })

  # if array has at least one element, assume it's host
  if (( ${#DATABASE[@]} > 0 )); then
    # assign host
    HOST=${DATABASE[0]}
  else
    # else set to localhost
    HOST=localhost
  fi

  if (( ${#DATABASE[@]} > 1 )); then
    # assign port
    PORT=${DATABASE[1]}
  else
    # else use default postgres port
    PORT=5432
  fi

  # wait for host to have open port
  until `nc -z $HOST $PORT`; do
    echo "Waiting on Postgres to come up..."
    sleep 10
  done
  # add some delay after port is up to validate that services are all up
  sleep 10
fi

# rest of run.sh file
```

I have not tested with other database backends or applied logic to verify that host and port are valid and I'm sure this code can get cleaned up some, so posting here as issue instead of a PR. Feel free to close if this is not something you wish to address in your official Docker image. 

Thanks, and great product!

**Comment by xlson** [comment]
Thanks for sharing your problem and solution! I don't think this is something we want in the main docker image but we might want to look into how to make Grafana itself a bit more forgiving.
