### ISSUE TITLE
Plugins installed but not available when creating a panel

### ISSUE THREAD

**Issue by mihalski** [grafana/grafana-docker#93]
Hi,

I followed the instructions for installing plugins during container creation:
```
sudo docker run -d --name grafana --restart=always -p 3000:3000 -e "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel,novalabs-annotations-panel,vonage-status-panel,fetzerch-sunandmoon-datasource,natel-discrete-panel,natel-influx-admin-panel" -v /docker/grafana:/var/lib/grafana grafana/grafana
```
This results in the plugins installing and being visible as installed in the web UI:
![screen shot 2017-06-05 08 37 18 pm](https://cloud.githubusercontent.com/assets/3755059/26784249/fba22c86-4a3f-11e7-9bb0-5f5652fa2bce.png)

However, when trying to create a new panel using the discrete plugin (for example) I get this:
![screen shot 2017-06-05 10 48 38 pm](https://cloud.githubusercontent.com/assets/3755059/26784474/2bb5d53e-4a41-11e7-85e1-c11418cf4d78.png)
The plugin doesn't appear to be available for use even though it is installed.

It is very definitively installed:
![screen shot 2017-06-05 10 43 33 pm](https://cloud.githubusercontent.com/assets/3755059/26784341/73ab1602-4a40-11e7-846f-2f7ad820690f.png)
The modified date has only changed due to macOS updating it due to me viewing the directory contents.

Any ideas on what could be happening here?
Thanks in advance.

Regards,
Michal

**Comment by daniellee** [comment]
Sounds like it could be browser caching. Have you tried doing a hard refresh? 

- [Hard refresh for Safari](https://apple.stackexchange.com/questions/12049/how-to-clear-the-cache-or-do-a-hard-refresh-in-safari)
- [Hard refresh for Chrome](https://superuser.com/a/512833/85532)

**Comment by 1043717432** [comment]
@mihalski  

Hi, mihalski, glad to find the latest your footprint, I used to see you in https://github.com/arendst/Sonoff-Tasmota/issues/83 using the Sonoff-Tasmota-IRremote code, I know you are using homeassistant, I have IR Emitter infrared transmitter on hand, and air-conditioning brand GREE, I have to get 16 hexadecimal code to express air conditioning, I in the Sonoff-Tasmota-IRremote firmware? Or how do you write it in Homeassistant? Thank you. Cheers!

**Comment by mihalski** [comment]
@daniellee You are absolutely right! I swear I tried the shift-refresh trick but it wasn't until I tried it on another OS with a browser that I hadn't previously used that it worked. Then I went back to my original system and browser, hit shift refresh and it worked like a charm!

Either way this makes me very happy :)

**Comment by mihalski** [comment]
@1043717432 I don't know if the IRremote library supports such codes. If you can find any info about them on the internet you might be able to make a request to have them included in the library. Then there's a chance of having it added to Tasmota.

With regards to how you would send the code, I suspect it would just be a matter of sending it via an MQTT topic from Home Assistant to where the Tasmota device is subscribed to it. It got a lot cooler so I don't have any need to work on automating my air conditioners at the moment.. But once it warms up again I'm sure I'll be looking at this again.
