### ISSUE TITLE
[Feature request]Please add sqlite3 package to official Grafana image

### ISSUE THREAD

**Issue by it-praktyk** [grafana/grafana-docker#97]
If any other database connection is not configured Grafana initiates default database using SQLite database.

Backup of a database can be performed using the command 

```
docker-compose exec grafana sqlite3 /var/lib/grafana/grafana.db .dump > ./grafana.sql
```
but required sqlite3 tool is not currently included in the Grafana Docker image.

Please install the sqlite3 package to allow perform SQL operation without installing custom images.

Thank you in advance.

**Comment by it-praktyk** [comment]
I can prepare a working solution for my feature request. Will it be accepted?

**Comment by bergquist** [comment]
Would it be easier to mount /data to the host and run the backup at the host instead?

**Comment by xlson** [comment]
We're currently trying to make the image smaller as its pretty easy to start sidecar containers with the tools you need we don't feel the main image should be bogged down by extras. In the future we might publish an alternative image with tools such as sqlite installed.
