### ISSUE TITLE
Grafana docker on mergerfs mount

### ISSUE THREAD

**Issue by Jeraimee** [grafana/grafana-docker#99]
While moving my `/var/lib/docker` directory to a mergerfs partition I found that when I `up`'d the grafana container it was failing with a message stating that `/usr/sbin/grafana-server` wasn't found.

Moving my docker directory back to a normal ext4 partition resolved the issue.

Mount options on the mergerfs mount are:

`defaults,use_ino,allow_other,minfreespace=50G,fsname=mergerfs,dropcacheonclose=true`

Note that `direct_io` is not enabled - this is to allow docker's socket sharing. While everything is running fine back on the ext4 partition I'd have no issues moving directories around and possibly playing with mount options if it'll help resolve this issue.

**Comment by xlson** [comment]
I'm afraid we know very little (nothing) of mergerfs here. Were you able to resolve your issue?
